// code auto-generated by ebnfcomp; do not modify!
// (code might get overwritten during next ebnfcomp invocation)

#include <stddef.h>

typedef enum _nodeclass_t {
    NC_TERMINAL,
    NC_PRODUCTION,
    NC_MANDATORY,
    NC_ALTERNATIVE,
    NC_OPTIONAL,
    NC_OPTIONAL_REPETITIVE,
} nodeclass_t;

typedef enum _terminaltype_t {
    TT_UNDEF,
    TT_STRING,
    TT_REGEX,
} terminaltype_t;

typedef enum _nodetype_t {
    _NT_GENERIC,
    NT_INT_LIT,
    NT_TERMINAL_1,
    NT_REAL_LIT,
    NT_TERMINAL_DOT,
    NT_TERMINAL_7,
    NT_TERMINAL_MINUS,
    NT_STR_LIT,
    NT_TERMINAL_11,
    NT_BOOL_LIT,
    NT_TERMINAL_TRUE,
    NT_TERMINAL_FALSE,
    NT_PTR_LIT,
    NT_TERMINAL_NIL,
    NT_IDENTIFIER,
    NT_TERMINAL_19,
    NT_BASE_TYPE,
    NT_TERMINAL_INT,
    NT_TERMINAL_REAL,
    NT_TERMINAL_STRING,
    NT_TERMINAL_BYTE,
    NT_TERMINAL_BOOL,
    NT_OBJECT_POINTER,
    NT_TERMINAL_XOR,
    NT_CELL_TYPE,
    NT_CELL_POINTER,
    NT_TERMINAL_STAR,
    NT_TYPE,
    NT_TYPE_LIST,
    NT_TERMINAL_COMMA,
    NT_NEG_OP,
    NT_TERMINAL_NOT,
    NT_MULT_OP,
    NT_TERMINAL_SLASH,
    NT_TERMINAL_MOD,
    NT_ADD_OP,
    NT_TERMINAL_PLUS,
    NT_SHF_OP,
    NT_TERMINAL_SHL,
    NT_TERMINAL_SHR,
    NT_CMP_OP,
    NT_TERMINAL_NE,
    NT_TERMINAL_LE,
    NT_TERMINAL_GE,
    NT_TERMINAL_EQ,
    NT_TERMINAL_LT,
    NT_TERMINAL_GT,
    NT_AND_OP,
    NT_TERMINAL_AND,
    NT_OR_OP,
    NT_TERMINAL_OR,
    NT_C_NUM_BASE_E,
    NT_TERMINAL_LPAREN,
    NT_TERMINAL_RPAREN,
    NT_C_NUM_NEG_E,
    NT_C_NUM_MULT_E,
    NT_C_NUM_ADD_E,
    NT_C_NUM_SHF_E,
    NT_C_NUM_CMP_E,
    NT_C_NUM_AND_E,
    NT_C_NUM_OR_E,
    NT_C_NUM_E,
    NT_C_STR_BASE_E,
    NT_C_STR_ADD_E,
    NT_C_STR_CMP_E,
    NT_C_STR_AND_E,
    NT_C_STR_OR_E,
    NT_C_STR_E,
    NT_C_BOOL_BASE_E,
    NT_C_BOOL_NOT_E,
    NT_C_BOOL_AND_E,
    NT_C_BOOL_OR_E,
    NT_C_BOOL_E,
    NT_C_PTR_E,
    NT_CONST_EXPR,
    NT_C_EXPR_LIST,
    NT_ACCESS_OP,
    NT_TERMINAL_150,
    NT_TERMINAL_LBRACK,
    NT_TERMINAL_RBRACK,
    NT_IDENT_ACCESS,
    NT_CALL_ACCESS,
    NT_VALOF_EXPR,
    NT_TERMINAL_VALOF,
    NT_NUM_BASE_E,
    NT_NUM_NEG_E,
    NT_NUM_MULT_E,
    NT_NUM_ADD_E,
    NT_NUM_SHF_E,
    NT_NUM_CMP_E,
    NT_NUM_AND_E,
    NT_NUM_OR_E,
    NT_NUM_E,
    NT_STR_BASE_E,
    NT_STR_ADD_E,
    NT_STR_CMP_E,
    NT_STR_AND_E,
    NT_STR_OR_E,
    NT_STR_E,
    NT_BOOL_BASE_E,
    NT_BOOL_NOT_E,
    NT_BOOL_AND_E,
    NT_BOOL_OR_E,
    NT_BOOL_E,
    NT_ARRAY_INST,
    NT_TERMINAL_DYNAMIC,
    NT_TERMINAL_ASSOC,
    NT_OBJECT_INST,
    NT_PTR_E,
    NT_TERMINAL_NEW,
    NT_EXPR,
    NT_EXPR_LIST,
    NT_CALL_ARG,
    NT_TERMINAL_257,
    NT_TERMINAL_DEFAULT,
    NT_CALL_ARG_LIST,
    NT_BLOCK,
    NT_TERMINAL_LBRACE,
    NT_TERMINAL_RBRACE,
    NT_OPTIONAL_BLOCK,
    NT_TERMINAL_SEMIC,
    NT_ARGUMENT_DECL,
    NT_TERMINAL_COLON,
    NT_TERMINAL_ELLIPSIS,
    NT_ARGUMENT_LIST,
    NT_ARG_DECLARATOR,
    NT_RETURN_DECL,
    NT_TERMINAL_RETURNING,
    NT_IDENT_LIST,
    NT_EXTENDS_CLAUSE,
    NT_TERMINAL_EXTENDS,
    NT_IMPL_CLAUSE,
    NT_TERMINAL_IMPLEMENTS,
    NT_VISIBILITY,
    NT_TERMINAL_PRIVATE,
    NT_TERMINAL_PROTECTED,
    NT_TERMINAL_PUBLIC,
    NT_ACCESS_TYPE,
    NT_TERMINAL_READONLY,
    NT_TERMINAL_READWRITE,
    NT_TERMINAL_WRITEONLY,
    NT_STORAGE_TYPE,
    NT_TERMINAL_STATIC,
    NT_DERIVATION,
    NT_TERMINAL_OVERRIDE,
    NT_TERMINAL_FINAL,
    NT_IMPLEMENTATION,
    NT_TERMINAL_IMPLEMENTATION,
    NT_ATTRIB_FLAG,
    NT_ATTRIB_FLAGS,
    NT_ATTRIB_DECL,
    NT_TERMINAL_ATTRIBUTE,
    NT_METHOD_FLAG,
    NT_METHOD_FLAGS,
    NT_METHOD_DECL,
    NT_TERMINAL_METHOD,
    NT_FIELD,
    NT_FIELD_LIST,
    NT_CLASS_DECL,
    NT_TERMINAL_CLASS,
    NT_IATTRIB_DECL,
    NT_IMETHOD_DECL,
    NT_IFIELD,
    NT_IFIELD_LIST,
    NT_INTERFACE_DECL,
    NT_TERMINAL_INTERFACE,
    NT_FUNC_DECL,
    NT_TERMINAL_FUNCTION,
    NT_PROC_DECL,
    NT_TERMINAL_PROCEDURE,
    NT_VAR_DECL,
    NT_TERMINAL_VAR,
    NT_CONST_DECL,
    NT_TERMINAL_CONST,
    NT_ENUM_ITEM,
    NT_ENUM_ITEM_LIST,
    NT_ENUM_DECL,
    NT_TERMINAL_ENUM,
    NT_LET_STMT,
    NT_TERMINAL_LET,
    NT_DECL_STMT,
    NT_BLOCK_DECL,
    NT_IMPORT_PATH,
    NT_IMPORT_LIST,
    NT_IMPORT_STMT,
    NT_TERMINAL_IMPORT,
    NT_XREF_TYPE,
    NT_TERMINAL_MODULE,
    NT_TERMINAL_PACKAGE,
    NT_TERMINAL_LIBRARY,
    NT_STR_LIT_LIST,
    NT_PLATFORM_SPEC,
    NT_TERMINAL_PLATFORM,
    NT_LANGUAGE_SPEC,
    NT_TERMINAL_LANGUAGE,
    NT_HEADER_SPEC,
    NT_TERMINAL_HEADER,
    NT_FUNCTION_SPEC,
    NT_PROCEDURE_SPEC,
    NT_CLASS_SPEC,
    NT_ALIEN_SPEC,
    NT_ALIEN_SPECS,
    NT_ALIEN_STMT,
    NT_TERMINAL_ALIEN,
    NT_GLOBAL_STMT,
    NT_GLOBAL_STMTS,
    NT_GLOBAL_INTRO,
    NT_GLOBAL_SPEC,
    NT_TERMINAL_PROGRAM,
    NT_GLOBAL_SCOPE,
    NT_LABEL_DECL,
    NT_CALL_STMT,
    NT_TERMINAL_CALL,
    NT_BLOCK_OR_STMT,
    NT_IF_STMT,
    NT_TERMINAL_IF,
    NT_TERMINAL_UNLESS,
    NT_TERMINAL_ELSE,
    NT_WHILE_STMT,
    NT_TERMINAL_WHILE,
    NT_TERMINAL_UNTIL,
    NT_REPEAT_STMT,
    NT_TERMINAL_REPEAT,
    NT_TERMINAL_DO,
    NT_LOOP_STMT,
    NT_TERMINAL_LOOP,
    NT_TERMINAL_FOREVER,
    NT_FOR_STMT,
    NT_TERMINAL_FOR,
    NT_TERMINAL_TO,
    NT_TERMINAL_DOWNTO,
    NT_LOOP_CONTROL,
    NT_TERMINAL_BREAK,
    NT_TERMINAL_CONTINUE,
    NT_TERMINAL_AGAIN,
    NT_LOOP_TYPE_STMT,
    NT_SWITCH_CASE,
    NT_TERMINAL_CASE,
    NT_DEFAULT_CASE,
    NT_ANY_CASE,
    NT_CASE_LIST,
    NT_SWITCH_STMT,
    NT_TERMINAL_SWITCH,
    NT_GOTO_STMT,
    NT_TERMINAL_GOTO,
    NT_TERMINAL_GOSUB,
    NT_RETURN_STMT,
    NT_TERMINAL_RETURN,
    NT_RESULTIS_STMT,
    NT_TERMINAL_RESULTIS,
    NT_DELETE_STMT,
    NT_TERMINAL_DELETE,
    NT_FLOW_CTRL_STMT,
    NT_STMT,
    NT_STATEMENT,
    NT_STATEMENT_LIST,
} nodetype_t;

typedef struct _parsingnode_t {
    nodeclass_t        nodeClass;
    nodetype_t         nodeType;
    terminaltype_t     termType;
    const char*        text;
    size_t             numBranches;
    int                branches;
} parsingnode_t;

// branches

static const int branches[777] = {
    // 0: production_int_lit branches
    1, 
    // 1: production_real_lit branches
    3, 
    // 2: mandatory_expr_3 branches
    0, 4, 0, 5, 
    // 6: optional_expr_5 branches
    6, 
    // 7: mandatory_expr_6 branches
    7, 8, 0, 
    // 10: optional_expr_8 branches
    9, 
    // 11: production_str_lit branches
    11, 
    // 12: production_bool_lit branches
    13, 
    // 13: alternative_expr_13 branches
    14, 15, 
    // 15: production_ptr_lit branches
    17, 
    // 16: production_identifier branches
    19, 
    // 17: production_base_type branches
    21, 
    // 18: alternative_expr_21 branches
    22, 23, 24, 25, 26, 
    // 23: production_object_pointer branches
    28, 
    // 24: mandatory_expr_28 branches
    18, 29, 
    // 26: production_cell_type branches
    31, 
    // 27: alternative_expr_31 branches
    20, 27, 
    // 29: production_cell_pointer branches
    33, 
    // 30: mandatory_expr_33 branches
    30, 34, 
    // 32: production_type branches
    36, 
    // 33: alternative_expr_36 branches
    32, 27, 20, 
    // 36: production_type_list branches
    38, 
    // 37: mandatory_expr_38 branches
    35, 39, 
    // 39: optional_repetitive_expr_39 branches
    40, 
    // 40: mandatory_expr_40 branches
    41, 35, 
    // 42: production_neg_op branches
    43, 
    // 43: alternative_expr_43 branches
    44, 45, 
    // 45: production_mult_op branches
    47, 
    // 46: alternative_expr_47 branches
    34, 48, 49, 
    // 49: production_add_op branches
    51, 
    // 50: alternative_expr_51 branches
    52, 9, 
    // 52: production_shf_op branches
    54, 
    // 53: alternative_expr_54 branches
    55, 56, 
    // 55: production_cmp_op branches
    58, 
    // 56: alternative_expr_58 branches
    59, 60, 61, 62, 63, 64, 
    // 62: production_and_op branches
    66, 
    // 63: production_or_op branches
    68, 
    // 64: alternative_expr_68 branches
    69, 70, 
    // 66: production_c_num_base_e branches
    72, 
    // 67: alternative_expr_72 branches
    2, 0, 73, 18, 
    // 71: mandatory_expr_73 branches
    74, 140, 75, 
    // 74: production_c_num_neg_e branches
    77, 
    // 75: mandatory_expr_77 branches
    78, 71, 
    // 77: optional_expr_78 branches
    42, 
    // 78: production_c_num_mult_e branches
    80, 
    // 79: mandatory_expr_80 branches
    76, 81, 
    // 81: optional_repetitive_expr_81 branches
    82, 
    // 82: mandatory_expr_82 branches
    46, 76, 
    // 84: production_c_num_add_e branches
    84, 
    // 85: mandatory_expr_84 branches
    79, 85, 
    // 87: optional_repetitive_expr_85 branches
    86, 
    // 88: mandatory_expr_86 branches
    50, 79, 
    // 90: production_c_num_shf_e branches
    88, 
    // 91: mandatory_expr_88 branches
    83, 89, 
    // 93: optional_expr_89 branches
    90, 
    // 94: mandatory_expr_90 branches
    53, 83, 
    // 96: production_c_num_cmp_e branches
    92, 
    // 97: mandatory_expr_92 branches
    87, 93, 
    // 99: optional_expr_93 branches
    94, 
    // 100: mandatory_expr_94 branches
    57, 87, 
    // 102: production_c_num_and_e branches
    96, 
    // 103: mandatory_expr_96 branches
    91, 97, 
    // 105: optional_repetitive_expr_97 branches
    98, 
    // 106: mandatory_expr_98 branches
    65, 91, 
    // 108: production_c_num_or_e branches
    100, 
    // 109: mandatory_expr_100 branches
    95, 101, 
    // 111: optional_repetitive_expr_101 branches
    102, 
    // 112: mandatory_expr_102 branches
    67, 95, 
    // 114: production_c_num_e branches
    99, 
    // 115: production_c_str_base_e branches
    105, 
    // 116: alternative_expr_105 branches
    10, 18, 
    // 118: production_c_str_add_e branches
    107, 
    // 119: mandatory_expr_107 branches
    200, 108, 
    // 121: optional_repetitive_expr_108 branches
    109, 
    // 122: mandatory_expr_109 branches
    110, 200, 
    // 124: production_c_str_cmp_e branches
    112, 
    // 125: mandatory_expr_112 branches
    106, 113, 
    // 127: optional_expr_113 branches
    114, 
    // 128: mandatory_expr_114 branches
    57, 106, 
    // 130: production_c_str_and_e branches
    116, 
    // 131: mandatory_expr_116 branches
    111, 117, 
    // 133: optional_repetitive_expr_117 branches
    118, 
    // 134: mandatory_expr_118 branches
    65, 111, 
    // 136: production_c_str_or_e branches
    120, 
    // 137: mandatory_expr_120 branches
    115, 121, 
    // 139: optional_repetitive_expr_121 branches
    122, 
    // 140: mandatory_expr_122 branches
    67, 115, 
    // 142: production_c_str_e branches
    119, 
    // 143: production_c_bool_base_e branches
    125, 
    // 144: alternative_expr_125 branches
    12, 18, 
    // 146: production_c_bool_not_e branches
    127, 
    // 147: mandatory_expr_127 branches
    128, 124, 
    // 149: optional_expr_128 branches
    129, 
    // 150: production_c_bool_and_e branches
    131, 
    // 151: mandatory_expr_131 branches
    126, 132, 
    // 153: optional_repetitive_expr_132 branches
    133, 
    // 154: mandatory_expr_133 branches
    65, 126, 
    // 156: production_c_bool_or_e branches
    135, 
    // 157: mandatory_expr_135 branches
    130, 136, 
    // 159: optional_repetitive_expr_136 branches
    137, 
    // 160: mandatory_expr_137 branches
    67, 130, 
    // 162: production_c_bool_e branches
    134, 
    // 163: production_c_ptr_e branches
    16, 
    // 164: production_const_expr branches
    141, 
    // 165: alternative_expr_141 branches
    103, 123, 138, 139, 
    // 169: production_c_expr_list branches
    143, 
    // 170: mandatory_expr_143 branches
    140, 144, 
    // 172: optional_repetitive_expr_144 branches
    145, 
    // 173: mandatory_expr_145 branches
    146, 140, 
    // 175: production_access_op branches
    148, 
    // 176: alternative_expr_148 branches
    149, 151, 
    // 178: mandatory_expr_149 branches
    150, 18, 
    // 180: mandatory_expr_151 branches
    152, 247, 153, 
    // 183: production_ident_access branches
    155, 
    // 184: mandatory_expr_155 branches
    18, 156, 157, 
    // 187: optional_repetitive_expr_156 branches
    147, 
    // 188: optional_expr_157 branches
    158, 
    // 189: mandatory_expr_158 branches
    159, 160, 161, 
    // 192: optional_expr_160 branches
    260, 
    // 193: production_call_access branches
    163, 
    // 194: mandatory_expr_163 branches
    18, 164, 165, 
    // 197: optional_repetitive_expr_164 branches
    147, 
    // 198: optional_expr_165 branches
    260, 
    // 199: production_valof_expr branches
    167, 
    // 200: mandatory_expr_167 branches
    168, 35, 264, 
    // 203: production_num_base_e branches
    170, 
    // 204: alternative_expr_170 branches
    2, 0, 171, 154, 166, 
    // 209: mandatory_expr_171 branches
    74, 247, 75, 
    // 212: production_num_neg_e branches
    173, 
    // 213: mandatory_expr_173 branches
    174, 169, 
    // 215: optional_expr_174 branches
    42, 
    // 216: production_num_mult_e branches
    176, 
    // 217: mandatory_expr_176 branches
    172, 177, 
    // 219: optional_repetitive_expr_177 branches
    178, 
    // 220: mandatory_expr_178 branches
    46, 172, 
    // 222: production_num_add_e branches
    180, 
    // 223: mandatory_expr_180 branches
    175, 181, 
    // 225: optional_repetitive_expr_181 branches
    182, 
    // 226: mandatory_expr_182 branches
    50, 175, 
    // 228: production_num_shf_e branches
    184, 
    // 229: mandatory_expr_184 branches
    179, 185, 
    // 231: optional_expr_185 branches
    186, 
    // 232: mandatory_expr_186 branches
    53, 179, 
    // 234: production_num_cmp_e branches
    188, 
    // 235: mandatory_expr_188 branches
    183, 189, 
    // 237: optional_expr_189 branches
    190, 
    // 238: mandatory_expr_190 branches
    57, 183, 
    // 240: production_num_and_e branches
    192, 
    // 241: mandatory_expr_192 branches
    187, 193, 
    // 243: optional_repetitive_expr_193 branches
    194, 
    // 244: mandatory_expr_194 branches
    65, 187, 
    // 246: production_num_or_e branches
    196, 
    // 247: mandatory_expr_196 branches
    191, 197, 
    // 249: optional_repetitive_expr_197 branches
    198, 
    // 250: mandatory_expr_198 branches
    67, 191, 
    // 252: production_num_e branches
    195, 
    // 253: production_str_base_e branches
    201, 
    // 254: alternative_expr_201 branches
    10, 154, 166, 
    // 257: production_str_add_e branches
    203, 
    // 258: mandatory_expr_203 branches
    200, 204, 
    // 260: optional_repetitive_expr_204 branches
    205, 
    // 261: mandatory_expr_205 branches
    52, 200, 
    // 263: production_str_cmp_e branches
    207, 
    // 264: mandatory_expr_207 branches
    202, 208, 
    // 266: optional_expr_208 branches
    209, 
    // 267: mandatory_expr_209 branches
    57, 202, 
    // 269: production_str_and_e branches
    211, 
    // 270: mandatory_expr_211 branches
    206, 212, 
    // 272: optional_repetitive_expr_212 branches
    213, 
    // 273: mandatory_expr_213 branches
    65, 206, 
    // 275: production_str_or_e branches
    215, 
    // 276: mandatory_expr_215 branches
    210, 216, 
    // 278: optional_repetitive_expr_216 branches
    217, 
    // 279: mandatory_expr_217 branches
    67, 210, 
    // 281: production_str_e branches
    214, 
    // 282: production_bool_base_e branches
    220, 
    // 283: alternative_expr_220 branches
    12, 154, 166, 
    // 286: production_bool_not_e branches
    222, 
    // 287: mandatory_expr_222 branches
    223, 219, 
    // 289: optional_expr_223 branches
    45, 
    // 290: production_bool_and_e branches
    225, 
    // 291: mandatory_expr_225 branches
    221, 226, 
    // 293: optional_repetitive_expr_226 branches
    227, 
    // 294: mandatory_expr_227 branches
    65, 221, 
    // 296: production_bool_or_e branches
    229, 
    // 297: mandatory_expr_229 branches
    224, 230, 
    // 299: optional_repetitive_expr_230 branches
    231, 
    // 300: mandatory_expr_231 branches
    67, 224, 
    // 302: production_bool_e branches
    228, 
    // 303: production_array_inst branches
    234, 
    // 304: mandatory_expr_234 branches
    152, 235, 153, 
    // 307: alternative_expr_235 branches
    236, 237, 199, 
    // 310: production_object_inst branches
    239, 
    // 311: mandatory_expr_239 branches
    74, 240, 75, 
    // 314: optional_expr_240 branches
    249, 
    // 315: production_ptr_e branches
    242, 
    // 316: alternative_expr_242 branches
    243, 16, 
    // 318: mandatory_expr_243 branches
    244, 35, 245, 
    // 321: optional_expr_245 branches
    246, 
    // 322: alternative_expr_246 branches
    233, 238, 
    // 324: production_expr branches
    248, 
    // 325: alternative_expr_248 branches
    199, 218, 232, 241, 
    // 329: production_expr_list branches
    250, 
    // 330: mandatory_expr_250 branches
    247, 251, 
    // 332: optional_repetitive_expr_251 branches
    252, 
    // 333: mandatory_expr_252 branches
    41, 247, 
    // 335: production_call_arg branches
    254, 
    // 336: mandatory_expr_254 branches
    255, 258, 
    // 338: optional_expr_255 branches
    256, 
    // 339: mandatory_expr_256 branches
    18, 257, 
    // 341: alternative_expr_258 branches
    259, 247, 
    // 343: production_call_arg_list branches
    261, 
    // 344: mandatory_expr_261 branches
    253, 262, 
    // 346: optional_repetitive_expr_262 branches
    263, 
    // 347: mandatory_expr_263 branches
    41, 253, 
    // 349: production_block branches
    265, 
    // 350: mandatory_expr_265 branches
    266, 267, 268, 
    // 353: optional_expr_267 branches
    544, 
    // 354: production_optional_block branches
    270, 
    // 355: alternative_expr_270 branches
    264, 271, 
    // 357: production_argument_decl branches
    273, 
    // 358: alternative_expr_273 branches
    274, 279, 
    // 360: mandatory_expr_274 branches
    291, 275, 35, 276, 
    // 364: optional_expr_276 branches
    277, 
    // 365: mandatory_expr_277 branches
    278, 142, 
    // 367: production_argument_list branches
    281, 
    // 368: mandatory_expr_281 branches
    272, 282, 
    // 370: optional_repetitive_expr_282 branches
    283, 
    // 371: mandatory_expr_283 branches
    284, 272, 
    // 373: production_arg_declarator branches
    286, 
    // 374: mandatory_expr_286 branches
    74, 287, 75, 
    // 377: optional_expr_287 branches
    280, 
    // 378: production_return_decl branches
    289, 
    // 379: mandatory_expr_289 branches
    290, 37, 
    // 381: production_ident_list branches
    292, 
    // 382: mandatory_expr_292 branches
    18, 293, 
    // 384: optional_repetitive_expr_293 branches
    294, 
    // 385: mandatory_expr_294 branches
    41, 18, 
    // 387: production_extends_clause branches
    296, 
    // 388: mandatory_expr_296 branches
    297, 291, 
    // 390: production_impl_clause branches
    299, 
    // 391: mandatory_expr_299 branches
    300, 291, 
    // 393: production_visibility branches
    302, 
    // 394: alternative_expr_302 branches
    303, 304, 305, 
    // 397: production_access_type branches
    307, 
    // 398: alternative_expr_307 branches
    308, 309, 310, 
    // 401: production_storage_type branches
    312, 
    // 402: production_derivation branches
    314, 
    // 403: alternative_expr_314 branches
    315, 316, 
    // 405: production_implementation branches
    318, 
    // 406: production_attrib_flag branches
    320, 
    // 407: alternative_expr_320 branches
    301, 306, 311, 313, 317, 
    // 412: production_attrib_flags branches
    322, 
    // 413: mandatory_expr_322 branches
    319, 323, 
    // 415: optional_repetitive_expr_323 branches
    319, 
    // 416: production_attrib_decl branches
    325, 
    // 417: mandatory_expr_325 branches
    326, 327, 291, 328, 35, 329, 271, 
    // 424: optional_expr_326 branches
    321, 
    // 425: optional_expr_329 branches
    330, 
    // 426: mandatory_expr_330 branches
    62, 142, 
    // 428: production_method_flag branches
    332, 
    // 429: alternative_expr_332 branches
    301, 311, 313, 317, 
    // 433: production_method_flags branches
    334, 
    // 434: mandatory_expr_334 branches
    331, 335, 
    // 436: optional_repetitive_expr_335 branches
    331, 
    // 437: production_method_decl branches
    337, 
    // 438: mandatory_expr_337 branches
    338, 339, 18, 285, 340, 269, 
    // 444: optional_expr_338 branches
    333, 
    // 445: optional_expr_340 branches
    288, 
    // 446: production_field branches
    342, 
    // 447: alternative_expr_342 branches
    324, 336, 381, 393, 
    // 451: production_field_list branches
    344, 
    // 452: mandatory_expr_344 branches
    341, 345, 
    // 454: optional_repetitive_expr_345 branches
    341, 
    // 455: production_class_decl branches
    347, 
    // 456: mandatory_expr_347 branches
    348, 18, 349, 350, 351, 352, 353, 
    // 463: optional_expr_349 branches
    295, 
    // 464: optional_expr_350 branches
    298, 
    // 465: optional_expr_352 branches
    343, 
    // 466: production_iattrib_decl branches
    355, 
    // 467: mandatory_expr_355 branches
    356, 327, 291, 275, 35, 271, 
    // 473: optional_expr_356 branches
    306, 
    // 474: production_imethod_decl branches
    358, 
    // 475: mandatory_expr_358 branches
    339, 18, 285, 359, 271, 
    // 480: optional_expr_359 branches
    288, 
    // 481: production_ifield branches
    361, 
    // 482: alternative_expr_361 branches
    354, 357, 381, 393, 
    // 486: production_ifield_list branches
    363, 
    // 487: mandatory_expr_363 branches
    360, 364, 
    // 489: optional_repetitive_expr_364 branches
    360, 
    // 490: production_interface_decl branches
    366, 
    // 491: mandatory_expr_366 branches
    367, 18, 368, 266, 369, 268, 
    // 497: optional_expr_368 branches
    295, 
    // 498: optional_expr_369 branches
    362, 
    // 499: production_func_decl branches
    371, 
    // 500: mandatory_expr_371 branches
    372, 373, 18, 285, 288, 269, 
    // 506: optional_expr_372 branches
    301, 
    // 507: production_proc_decl branches
    375, 
    // 508: mandatory_expr_375 branches
    376, 377, 18, 285, 269, 
    // 513: optional_expr_376 branches
    301, 
    // 514: production_var_decl branches
    379, 
    // 515: mandatory_expr_379 branches
    380, 291, 275, 35, 271, 
    // 520: production_const_decl branches
    382, 
    // 521: mandatory_expr_382 branches
    383, 291, 62, 142, 271, 
    // 526: production_enum_item branches
    385, 
    // 527: mandatory_expr_385 branches
    18, 386, 
    // 529: optional_expr_386 branches
    387, 
    // 530: mandatory_expr_387 branches
    62, 140, 
    // 532: production_enum_item_list branches
    389, 
    // 533: mandatory_expr_389 branches
    384, 390, 392, 
    // 536: optional_repetitive_expr_390 branches
    391, 
    // 537: mandatory_expr_391 branches
    41, 384, 
    // 539: optional_expr_392 branches
    41, 
    // 540: production_enum_decl branches
    394, 
    // 541: mandatory_expr_394 branches
    395, 18, 266, 388, 268, 
    // 546: production_let_stmt branches
    397, 
    // 547: mandatory_expr_397 branches
    398, 291, 62, 249, 271, 
    // 552: production_decl_stmt branches
    400, 
    // 553: alternative_expr_400 branches
    346, 365, 381, 393, 370, 374, 378, 
    // 560: production_block_decl branches
    402, 
    // 561: alternative_expr_402 branches
    381, 393, 378, 
    // 564: production_import_path branches
    404, 
    // 565: mandatory_expr_404 branches
    18, 405, 
    // 567: optional_repetitive_expr_405 branches
    406, 
    // 568: mandatory_expr_406 branches
    48, 18, 
    // 570: production_import_list branches
    408, 
    // 571: mandatory_expr_408 branches
    403, 409, 
    // 573: optional_repetitive_expr_409 branches
    410, 
    // 574: mandatory_expr_410 branches
    41, 403, 
    // 576: production_import_stmt branches
    412, 
    // 577: mandatory_expr_412 branches
    413, 403, 271, 
    // 580: production_xref_type branches
    415, 
    // 581: alternative_expr_415 branches
    416, 417, 418, 
    // 584: production_str_lit_list branches
    420, 
    // 585: mandatory_expr_420 branches
    10, 421, 
    // 587: optional_repetitive_expr_421 branches
    422, 
    // 588: mandatory_expr_422 branches
    41, 10, 
    // 590: production_platform_spec branches
    424, 
    // 591: mandatory_expr_424 branches
    425, 419, 
    // 593: production_language_spec branches
    427, 
    // 594: mandatory_expr_427 branches
    428, 419, 
    // 596: production_header_spec branches
    430, 
    // 597: mandatory_expr_430 branches
    431, 419, 
    // 599: production_function_spec branches
    433, 
    // 600: mandatory_expr_433 branches
    373, 419, 
    // 602: production_procedure_spec branches
    435, 
    // 603: mandatory_expr_435 branches
    377, 419, 
    // 605: production_class_spec branches
    437, 
    // 606: mandatory_expr_437 branches
    348, 419, 
    // 608: production_alien_spec branches
    439, 
    // 609: alternative_expr_439 branches
    423, 426, 429, 432, 434, 436, 
    // 615: production_alien_specs branches
    441, 
    // 616: mandatory_expr_441 branches
    438, 442, 
    // 618: optional_repetitive_expr_442 branches
    443, 
    // 619: mandatory_expr_443 branches
    41, 438, 
    // 621: production_alien_stmt branches
    445, 
    // 622: mandatory_expr_445 branches
    446, 414, 18, 447, 271, 
    // 627: optional_expr_447 branches
    448, 
    // 628: mandatory_expr_448 branches
    41, 440, 
    // 630: production_global_stmt branches
    399, 
    // 631: production_global_stmts branches
    451, 
    // 632: mandatory_expr_451 branches
    399, 452, 
    // 634: optional_repetitive_expr_452 branches
    399, 
    // 635: production_global_intro branches
    454, 
    // 636: alternative_expr_454 branches
    411, 444, 
    // 638: production_global_spec branches
    456, 
    // 639: mandatory_expr_456 branches
    457, 18, 271, 
    // 642: alternative_expr_457 branches
    458, 414, 
    // 644: production_global_scope branches
    460, 
    // 645: mandatory_expr_460 branches
    461, 462, 463, 
    // 648: optional_expr_461 branches
    455, 
    // 649: optional_repetitive_expr_462 branches
    453, 
    // 650: optional_repetitive_expr_463 branches
    450, 
    // 651: production_label_decl branches
    465, 
    // 652: mandatory_expr_465 branches
    18, 275, 
    // 654: production_call_stmt branches
    467, 
    // 655: mandatory_expr_467 branches
    468, 162, 271, 
    // 658: production_block_or_stmt branches
    470, 
    // 659: alternative_expr_470 branches
    264, 539, 
    // 661: production_if_stmt branches
    472, 
    // 662: mandatory_expr_472 branches
    473, 247, 469, 476, 
    // 666: alternative_expr_473 branches
    474, 475, 
    // 668: optional_expr_476 branches
    477, 
    // 669: mandatory_expr_477 branches
    478, 469, 
    // 671: production_while_stmt branches
    480, 
    // 672: mandatory_expr_480 branches
    481, 247, 469, 
    // 675: alternative_expr_481 branches
    482, 483, 
    // 677: production_repeat_stmt branches
    485, 
    // 678: mandatory_expr_485 branches
    486, 264, 489, 247, 271, 
    // 683: alternative_expr_486 branches
    487, 488, 
    // 685: alternative_expr_489 branches
    482, 483, 
    // 687: production_loop_stmt branches
    491, 
    // 688: mandatory_expr_491 branches
    492, 469, 
    // 690: alternative_expr_492 branches
    493, 494, 
    // 692: production_for_stmt branches
    496, 
    // 693: mandatory_expr_496 branches
    497, 18, 62, 247, 498, 247, 488, 469, 
    // 701: alternative_expr_498 branches
    499, 500, 
    // 703: production_loop_control branches
    502, 
    // 704: mandatory_expr_502 branches
    503, 507, 271, 
    // 707: alternative_expr_503 branches
    504, 505, 506, 
    // 710: optional_expr_507 branches
    18, 
    // 711: production_loop_type_stmt branches
    509, 
    // 712: alternative_expr_509 branches
    479, 484, 490, 495, 501, 
    // 717: production_switch_case branches
    511, 
    // 718: mandatory_expr_511 branches
    512, 142, 275, 469, 
    // 722: production_default_case branches
    514, 
    // 723: mandatory_expr_514 branches
    259, 275, 469, 
    // 726: production_any_case branches
    516, 
    // 727: alternative_expr_516 branches
    510, 513, 
    // 729: production_case_list branches
    518, 
    // 730: mandatory_expr_518 branches
    515, 519, 
    // 732: optional_repetitive_expr_519 branches
    515, 
    // 733: production_switch_stmt branches
    521, 
    // 734: mandatory_expr_521 branches
    522, 247, 266, 517, 268, 
    // 739: production_goto_stmt branches
    524, 
    // 740: mandatory_expr_524 branches
    525, 18, 271, 
    // 743: alternative_expr_525 branches
    526, 527, 
    // 745: production_return_stmt branches
    529, 
    // 746: mandatory_expr_529 branches
    530, 271, 
    // 748: production_resultis_stmt branches
    532, 
    // 749: mandatory_expr_532 branches
    533, 249, 271, 
    // 752: production_delete_stmt branches
    535, 
    // 753: mandatory_expr_535 branches
    536, 291, 271, 
    // 756: production_flow_ctrl_stmt branches
    538, 
    // 757: alternative_expr_538 branches
    471, 508, 520, 523, 528, 531, 466, 534, 
    // 765: production_stmt branches
    540, 
    // 766: alternative_expr_540 branches
    401, 396, 537, 
    // 769: production_statement branches
    542, 
    // 770: mandatory_expr_542 branches
    543, 539, 
    // 772: optional_expr_543 branches
    464, 
    // 773: production_statement_list branches
    545, 
    // 774: mandatory_expr_545 branches
    541, 546, 
    // 776: optional_repetitive_expr_546 branches
    541, 
};

static const parsingnode_t parsingTable[547] = {
    // 0: production_int_lit
    { NC_PRODUCTION, NT_INT_LIT, TT_UNDEF, 0, 1, 0 },
    // 1: regex_terminal_1
    { NC_TERMINAL, NT_TERMINAL_1, TT_REGEX, "[0-9]+", 0, -1 },
    // 2: production_real_lit
    { NC_PRODUCTION, NT_REAL_LIT, TT_UNDEF, 0, 1, 1 },
    // 3: mandatory_expr_3
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 4, 2 },
    // 4: string_terminal_4
    { NC_TERMINAL, NT_TERMINAL_DOT, TT_STRING, ".", 0, -1 },
    // 5: optional_expr_5
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 6 },
    // 6: mandatory_expr_6
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 7 },
    // 7: regex_terminal_7
    { NC_TERMINAL, NT_TERMINAL_7, TT_REGEX, "[eE]", 0, -1 },
    // 8: optional_expr_8
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 10 },
    // 9: string_terminal_9
    { NC_TERMINAL, NT_TERMINAL_MINUS, TT_STRING, "-", 0, -1 },
    // 10: production_str_lit
    { NC_PRODUCTION, NT_STR_LIT, TT_UNDEF, 0, 1, 11 },
    // 11: regex_terminal_11
    { NC_TERMINAL, NT_TERMINAL_11, TT_REGEX, "\"[^\"]+\"", 0, -1 },
    // 12: production_bool_lit
    { NC_PRODUCTION, NT_BOOL_LIT, TT_UNDEF, 0, 1, 12 },
    // 13: alternative_expr_13
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 13 },
    // 14: string_terminal_14
    { NC_TERMINAL, NT_TERMINAL_TRUE, TT_STRING, "true", 0, -1 },
    // 15: string_terminal_15
    { NC_TERMINAL, NT_TERMINAL_FALSE, TT_STRING, "false", 0, -1 },
    // 16: production_ptr_lit
    { NC_PRODUCTION, NT_PTR_LIT, TT_UNDEF, 0, 1, 15 },
    // 17: string_terminal_17
    { NC_TERMINAL, NT_TERMINAL_NIL, TT_STRING, "nil", 0, -1 },
    // 18: production_identifier
    { NC_PRODUCTION, NT_IDENTIFIER, TT_UNDEF, 0, 1, 16 },
    // 19: regex_terminal_19
    { NC_TERMINAL, NT_TERMINAL_19, TT_REGEX, "[a-zA-Z_][a-zA-Z0-9_]*", 0, -1 },
    // 20: production_base_type
    { NC_PRODUCTION, NT_BASE_TYPE, TT_UNDEF, 0, 1, 17 },
    // 21: alternative_expr_21
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 5, 18 },
    // 22: string_terminal_22
    { NC_TERMINAL, NT_TERMINAL_INT, TT_STRING, "int", 0, -1 },
    // 23: string_terminal_23
    { NC_TERMINAL, NT_TERMINAL_REAL, TT_STRING, "real", 0, -1 },
    // 24: string_terminal_24
    { NC_TERMINAL, NT_TERMINAL_STRING, TT_STRING, "string", 0, -1 },
    // 25: string_terminal_25
    { NC_TERMINAL, NT_TERMINAL_BYTE, TT_STRING, "byte", 0, -1 },
    // 26: string_terminal_26
    { NC_TERMINAL, NT_TERMINAL_BOOL, TT_STRING, "bool", 0, -1 },
    // 27: production_object_pointer
    { NC_PRODUCTION, NT_OBJECT_POINTER, TT_UNDEF, 0, 1, 23 },
    // 28: mandatory_expr_28
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 24 },
    // 29: string_terminal_29
    { NC_TERMINAL, NT_TERMINAL_XOR, TT_STRING, "^", 0, -1 },
    // 30: production_cell_type
    { NC_PRODUCTION, NT_CELL_TYPE, TT_UNDEF, 0, 1, 26 },
    // 31: alternative_expr_31
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 27 },
    // 32: production_cell_pointer
    { NC_PRODUCTION, NT_CELL_POINTER, TT_UNDEF, 0, 1, 29 },
    // 33: mandatory_expr_33
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 30 },
    // 34: string_terminal_34
    { NC_TERMINAL, NT_TERMINAL_STAR, TT_STRING, "*", 0, -1 },
    // 35: production_type
    { NC_PRODUCTION, NT_TYPE, TT_UNDEF, 0, 1, 32 },
    // 36: alternative_expr_36
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 33 },
    // 37: production_type_list
    { NC_PRODUCTION, NT_TYPE_LIST, TT_UNDEF, 0, 1, 36 },
    // 38: mandatory_expr_38
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 37 },
    // 39: optional_repetitive_expr_39
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 39 },
    // 40: mandatory_expr_40
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 40 },
    // 41: string_terminal_41
    { NC_TERMINAL, NT_TERMINAL_COMMA, TT_STRING, ",", 0, -1 },
    // 42: production_neg_op
    { NC_PRODUCTION, NT_NEG_OP, TT_UNDEF, 0, 1, 42 },
    // 43: alternative_expr_43
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 43 },
    // 44: string_terminal_44
    { NC_TERMINAL, NT_TERMINAL_MINUS, TT_STRING, "-", 0, -1 },
    // 45: string_terminal_45
    { NC_TERMINAL, NT_TERMINAL_NOT, TT_STRING, "not", 0, -1 },
    // 46: production_mult_op
    { NC_PRODUCTION, NT_MULT_OP, TT_UNDEF, 0, 1, 45 },
    // 47: alternative_expr_47
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 46 },
    // 48: string_terminal_48
    { NC_TERMINAL, NT_TERMINAL_SLASH, TT_STRING, "/", 0, -1 },
    // 49: string_terminal_49
    { NC_TERMINAL, NT_TERMINAL_MOD, TT_STRING, "mod", 0, -1 },
    // 50: production_add_op
    { NC_PRODUCTION, NT_ADD_OP, TT_UNDEF, 0, 1, 49 },
    // 51: alternative_expr_51
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 50 },
    // 52: string_terminal_52
    { NC_TERMINAL, NT_TERMINAL_PLUS, TT_STRING, "+", 0, -1 },
    // 53: production_shf_op
    { NC_PRODUCTION, NT_SHF_OP, TT_UNDEF, 0, 1, 52 },
    // 54: alternative_expr_54
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 53 },
    // 55: string_terminal_55
    { NC_TERMINAL, NT_TERMINAL_SHL, TT_STRING, "shl", 0, -1 },
    // 56: string_terminal_56
    { NC_TERMINAL, NT_TERMINAL_SHR, TT_STRING, "shr", 0, -1 },
    // 57: production_cmp_op
    { NC_PRODUCTION, NT_CMP_OP, TT_UNDEF, 0, 1, 55 },
    // 58: alternative_expr_58
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 6, 56 },
    // 59: string_terminal_59
    { NC_TERMINAL, NT_TERMINAL_NE, TT_STRING, "<>", 0, -1 },
    // 60: string_terminal_60
    { NC_TERMINAL, NT_TERMINAL_LE, TT_STRING, "<=", 0, -1 },
    // 61: string_terminal_61
    { NC_TERMINAL, NT_TERMINAL_GE, TT_STRING, ">=", 0, -1 },
    // 62: string_terminal_62
    { NC_TERMINAL, NT_TERMINAL_EQ, TT_STRING, "=", 0, -1 },
    // 63: string_terminal_63
    { NC_TERMINAL, NT_TERMINAL_LT, TT_STRING, "<", 0, -1 },
    // 64: string_terminal_64
    { NC_TERMINAL, NT_TERMINAL_GT, TT_STRING, ">", 0, -1 },
    // 65: production_and_op
    { NC_PRODUCTION, NT_AND_OP, TT_UNDEF, 0, 1, 62 },
    // 66: string_terminal_66
    { NC_TERMINAL, NT_TERMINAL_AND, TT_STRING, "and", 0, -1 },
    // 67: production_or_op
    { NC_PRODUCTION, NT_OR_OP, TT_UNDEF, 0, 1, 63 },
    // 68: alternative_expr_68
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 64 },
    // 69: string_terminal_69
    { NC_TERMINAL, NT_TERMINAL_OR, TT_STRING, "or", 0, -1 },
    // 70: string_terminal_70
    { NC_TERMINAL, NT_TERMINAL_XOR, TT_STRING, "xor", 0, -1 },
    // 71: production_c_num_base_e
    { NC_PRODUCTION, NT_C_NUM_BASE_E, TT_UNDEF, 0, 1, 66 },
    // 72: alternative_expr_72
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 4, 67 },
    // 73: mandatory_expr_73
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 71 },
    // 74: string_terminal_74
    { NC_TERMINAL, NT_TERMINAL_LPAREN, TT_STRING, "(", 0, -1 },
    // 75: string_terminal_75
    { NC_TERMINAL, NT_TERMINAL_RPAREN, TT_STRING, ")", 0, -1 },
    // 76: production_c_num_neg_e
    { NC_PRODUCTION, NT_C_NUM_NEG_E, TT_UNDEF, 0, 1, 74 },
    // 77: mandatory_expr_77
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 75 },
    // 78: optional_expr_78
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 77 },
    // 79: production_c_num_mult_e
    { NC_PRODUCTION, NT_C_NUM_MULT_E, TT_UNDEF, 0, 1, 78 },
    // 80: mandatory_expr_80
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 79 },
    // 81: optional_repetitive_expr_81
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 81 },
    // 82: mandatory_expr_82
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 82 },
    // 83: production_c_num_add_e
    { NC_PRODUCTION, NT_C_NUM_ADD_E, TT_UNDEF, 0, 1, 84 },
    // 84: mandatory_expr_84
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 85 },
    // 85: optional_repetitive_expr_85
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 87 },
    // 86: mandatory_expr_86
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 88 },
    // 87: production_c_num_shf_e
    { NC_PRODUCTION, NT_C_NUM_SHF_E, TT_UNDEF, 0, 1, 90 },
    // 88: mandatory_expr_88
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 91 },
    // 89: optional_expr_89
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 93 },
    // 90: mandatory_expr_90
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 94 },
    // 91: production_c_num_cmp_e
    { NC_PRODUCTION, NT_C_NUM_CMP_E, TT_UNDEF, 0, 1, 96 },
    // 92: mandatory_expr_92
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 97 },
    // 93: optional_expr_93
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 99 },
    // 94: mandatory_expr_94
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 100 },
    // 95: production_c_num_and_e
    { NC_PRODUCTION, NT_C_NUM_AND_E, TT_UNDEF, 0, 1, 102 },
    // 96: mandatory_expr_96
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 103 },
    // 97: optional_repetitive_expr_97
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 105 },
    // 98: mandatory_expr_98
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 106 },
    // 99: production_c_num_or_e
    { NC_PRODUCTION, NT_C_NUM_OR_E, TT_UNDEF, 0, 1, 108 },
    // 100: mandatory_expr_100
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 109 },
    // 101: optional_repetitive_expr_101
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 111 },
    // 102: mandatory_expr_102
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 112 },
    // 103: production_c_num_e
    { NC_PRODUCTION, NT_C_NUM_E, TT_UNDEF, 0, 1, 114 },
    // 104: production_c_str_base_e
    { NC_PRODUCTION, NT_C_STR_BASE_E, TT_UNDEF, 0, 1, 115 },
    // 105: alternative_expr_105
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 116 },
    // 106: production_c_str_add_e
    { NC_PRODUCTION, NT_C_STR_ADD_E, TT_UNDEF, 0, 1, 118 },
    // 107: mandatory_expr_107
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 119 },
    // 108: optional_repetitive_expr_108
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 121 },
    // 109: mandatory_expr_109
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 122 },
    // 110: string_terminal_110
    { NC_TERMINAL, NT_TERMINAL_PLUS, TT_STRING, "+", 0, -1 },
    // 111: production_c_str_cmp_e
    { NC_PRODUCTION, NT_C_STR_CMP_E, TT_UNDEF, 0, 1, 124 },
    // 112: mandatory_expr_112
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 125 },
    // 113: optional_expr_113
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 127 },
    // 114: mandatory_expr_114
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 128 },
    // 115: production_c_str_and_e
    { NC_PRODUCTION, NT_C_STR_AND_E, TT_UNDEF, 0, 1, 130 },
    // 116: mandatory_expr_116
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 131 },
    // 117: optional_repetitive_expr_117
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 133 },
    // 118: mandatory_expr_118
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 134 },
    // 119: production_c_str_or_e
    { NC_PRODUCTION, NT_C_STR_OR_E, TT_UNDEF, 0, 1, 136 },
    // 120: mandatory_expr_120
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 137 },
    // 121: optional_repetitive_expr_121
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 139 },
    // 122: mandatory_expr_122
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 140 },
    // 123: production_c_str_e
    { NC_PRODUCTION, NT_C_STR_E, TT_UNDEF, 0, 1, 142 },
    // 124: production_c_bool_base_e
    { NC_PRODUCTION, NT_C_BOOL_BASE_E, TT_UNDEF, 0, 1, 143 },
    // 125: alternative_expr_125
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 144 },
    // 126: production_c_bool_not_e
    { NC_PRODUCTION, NT_C_BOOL_NOT_E, TT_UNDEF, 0, 1, 146 },
    // 127: mandatory_expr_127
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 147 },
    // 128: optional_expr_128
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 149 },
    // 129: string_terminal_129
    { NC_TERMINAL, NT_TERMINAL_NOT, TT_STRING, "not", 0, -1 },
    // 130: production_c_bool_and_e
    { NC_PRODUCTION, NT_C_BOOL_AND_E, TT_UNDEF, 0, 1, 150 },
    // 131: mandatory_expr_131
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 151 },
    // 132: optional_repetitive_expr_132
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 153 },
    // 133: mandatory_expr_133
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 154 },
    // 134: production_c_bool_or_e
    { NC_PRODUCTION, NT_C_BOOL_OR_E, TT_UNDEF, 0, 1, 156 },
    // 135: mandatory_expr_135
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 157 },
    // 136: optional_repetitive_expr_136
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 159 },
    // 137: mandatory_expr_137
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 160 },
    // 138: production_c_bool_e
    { NC_PRODUCTION, NT_C_BOOL_E, TT_UNDEF, 0, 1, 162 },
    // 139: production_c_ptr_e
    { NC_PRODUCTION, NT_C_PTR_E, TT_UNDEF, 0, 1, 163 },
    // 140: production_const_expr
    { NC_PRODUCTION, NT_CONST_EXPR, TT_UNDEF, 0, 1, 164 },
    // 141: alternative_expr_141
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 4, 165 },
    // 142: production_c_expr_list
    { NC_PRODUCTION, NT_C_EXPR_LIST, TT_UNDEF, 0, 1, 169 },
    // 143: mandatory_expr_143
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 170 },
    // 144: optional_repetitive_expr_144
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 172 },
    // 145: mandatory_expr_145
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 173 },
    // 146: string_terminal_146
    { NC_TERMINAL, NT_TERMINAL_COMMA, TT_STRING, ",", 0, -1 },
    // 147: production_access_op
    { NC_PRODUCTION, NT_ACCESS_OP, TT_UNDEF, 0, 1, 175 },
    // 148: alternative_expr_148
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 176 },
    // 149: mandatory_expr_149
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 178 },
    // 150: string_terminal_150
    { NC_TERMINAL, NT_TERMINAL_150, TT_STRING, "->", 0, -1 },
    // 151: mandatory_expr_151
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 180 },
    // 152: string_terminal_152
    { NC_TERMINAL, NT_TERMINAL_LBRACK, TT_STRING, "[", 0, -1 },
    // 153: string_terminal_153
    { NC_TERMINAL, NT_TERMINAL_RBRACK, TT_STRING, "]", 0, -1 },
    // 154: production_ident_access
    { NC_PRODUCTION, NT_IDENT_ACCESS, TT_UNDEF, 0, 1, 183 },
    // 155: mandatory_expr_155
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 184 },
    // 156: optional_repetitive_expr_156
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 187 },
    // 157: optional_expr_157
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 188 },
    // 158: mandatory_expr_158
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 189 },
    // 159: string_terminal_159
    { NC_TERMINAL, NT_TERMINAL_LPAREN, TT_STRING, "(", 0, -1 },
    // 160: optional_expr_160
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 192 },
    // 161: string_terminal_161
    { NC_TERMINAL, NT_TERMINAL_RPAREN, TT_STRING, ")", 0, -1 },
    // 162: production_call_access
    { NC_PRODUCTION, NT_CALL_ACCESS, TT_UNDEF, 0, 1, 193 },
    // 163: mandatory_expr_163
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 194 },
    // 164: optional_repetitive_expr_164
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 197 },
    // 165: optional_expr_165
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 198 },
    // 166: production_valof_expr
    { NC_PRODUCTION, NT_VALOF_EXPR, TT_UNDEF, 0, 1, 199 },
    // 167: mandatory_expr_167
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 200 },
    // 168: string_terminal_168
    { NC_TERMINAL, NT_TERMINAL_VALOF, TT_STRING, "valof", 0, -1 },
    // 169: production_num_base_e
    { NC_PRODUCTION, NT_NUM_BASE_E, TT_UNDEF, 0, 1, 203 },
    // 170: alternative_expr_170
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 5, 204 },
    // 171: mandatory_expr_171
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 209 },
    // 172: production_num_neg_e
    { NC_PRODUCTION, NT_NUM_NEG_E, TT_UNDEF, 0, 1, 212 },
    // 173: mandatory_expr_173
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 213 },
    // 174: optional_expr_174
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 215 },
    // 175: production_num_mult_e
    { NC_PRODUCTION, NT_NUM_MULT_E, TT_UNDEF, 0, 1, 216 },
    // 176: mandatory_expr_176
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 217 },
    // 177: optional_repetitive_expr_177
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 219 },
    // 178: mandatory_expr_178
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 220 },
    // 179: production_num_add_e
    { NC_PRODUCTION, NT_NUM_ADD_E, TT_UNDEF, 0, 1, 222 },
    // 180: mandatory_expr_180
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 223 },
    // 181: optional_repetitive_expr_181
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 225 },
    // 182: mandatory_expr_182
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 226 },
    // 183: production_num_shf_e
    { NC_PRODUCTION, NT_NUM_SHF_E, TT_UNDEF, 0, 1, 228 },
    // 184: mandatory_expr_184
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 229 },
    // 185: optional_expr_185
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 231 },
    // 186: mandatory_expr_186
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 232 },
    // 187: production_num_cmp_e
    { NC_PRODUCTION, NT_NUM_CMP_E, TT_UNDEF, 0, 1, 234 },
    // 188: mandatory_expr_188
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 235 },
    // 189: optional_expr_189
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 237 },
    // 190: mandatory_expr_190
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 238 },
    // 191: production_num_and_e
    { NC_PRODUCTION, NT_NUM_AND_E, TT_UNDEF, 0, 1, 240 },
    // 192: mandatory_expr_192
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 241 },
    // 193: optional_repetitive_expr_193
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 243 },
    // 194: mandatory_expr_194
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 244 },
    // 195: production_num_or_e
    { NC_PRODUCTION, NT_NUM_OR_E, TT_UNDEF, 0, 1, 246 },
    // 196: mandatory_expr_196
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 247 },
    // 197: optional_repetitive_expr_197
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 249 },
    // 198: mandatory_expr_198
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 250 },
    // 199: production_num_e
    { NC_PRODUCTION, NT_NUM_E, TT_UNDEF, 0, 1, 252 },
    // 200: production_str_base_e
    { NC_PRODUCTION, NT_STR_BASE_E, TT_UNDEF, 0, 1, 253 },
    // 201: alternative_expr_201
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 254 },
    // 202: production_str_add_e
    { NC_PRODUCTION, NT_STR_ADD_E, TT_UNDEF, 0, 1, 257 },
    // 203: mandatory_expr_203
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 258 },
    // 204: optional_repetitive_expr_204
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 260 },
    // 205: mandatory_expr_205
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 261 },
    // 206: production_str_cmp_e
    { NC_PRODUCTION, NT_STR_CMP_E, TT_UNDEF, 0, 1, 263 },
    // 207: mandatory_expr_207
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 264 },
    // 208: optional_expr_208
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 266 },
    // 209: mandatory_expr_209
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 267 },
    // 210: production_str_and_e
    { NC_PRODUCTION, NT_STR_AND_E, TT_UNDEF, 0, 1, 269 },
    // 211: mandatory_expr_211
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 270 },
    // 212: optional_repetitive_expr_212
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 272 },
    // 213: mandatory_expr_213
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 273 },
    // 214: production_str_or_e
    { NC_PRODUCTION, NT_STR_OR_E, TT_UNDEF, 0, 1, 275 },
    // 215: mandatory_expr_215
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 276 },
    // 216: optional_repetitive_expr_216
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 278 },
    // 217: mandatory_expr_217
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 279 },
    // 218: production_str_e
    { NC_PRODUCTION, NT_STR_E, TT_UNDEF, 0, 1, 281 },
    // 219: production_bool_base_e
    { NC_PRODUCTION, NT_BOOL_BASE_E, TT_UNDEF, 0, 1, 282 },
    // 220: alternative_expr_220
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 283 },
    // 221: production_bool_not_e
    { NC_PRODUCTION, NT_BOOL_NOT_E, TT_UNDEF, 0, 1, 286 },
    // 222: mandatory_expr_222
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 287 },
    // 223: optional_expr_223
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 289 },
    // 224: production_bool_and_e
    { NC_PRODUCTION, NT_BOOL_AND_E, TT_UNDEF, 0, 1, 290 },
    // 225: mandatory_expr_225
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 291 },
    // 226: optional_repetitive_expr_226
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 293 },
    // 227: mandatory_expr_227
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 294 },
    // 228: production_bool_or_e
    { NC_PRODUCTION, NT_BOOL_OR_E, TT_UNDEF, 0, 1, 296 },
    // 229: mandatory_expr_229
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 297 },
    // 230: optional_repetitive_expr_230
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 299 },
    // 231: mandatory_expr_231
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 300 },
    // 232: production_bool_e
    { NC_PRODUCTION, NT_BOOL_E, TT_UNDEF, 0, 1, 302 },
    // 233: production_array_inst
    { NC_PRODUCTION, NT_ARRAY_INST, TT_UNDEF, 0, 1, 303 },
    // 234: mandatory_expr_234
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 304 },
    // 235: alternative_expr_235
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 307 },
    // 236: string_terminal_236
    { NC_TERMINAL, NT_TERMINAL_DYNAMIC, TT_STRING, "dynamic", 0, -1 },
    // 237: string_terminal_237
    { NC_TERMINAL, NT_TERMINAL_ASSOC, TT_STRING, "assoc", 0, -1 },
    // 238: production_object_inst
    { NC_PRODUCTION, NT_OBJECT_INST, TT_UNDEF, 0, 1, 310 },
    // 239: mandatory_expr_239
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 311 },
    // 240: optional_expr_240
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 314 },
    // 241: production_ptr_e
    { NC_PRODUCTION, NT_PTR_E, TT_UNDEF, 0, 1, 315 },
    // 242: alternative_expr_242
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 316 },
    // 243: mandatory_expr_243
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 318 },
    // 244: string_terminal_244
    { NC_TERMINAL, NT_TERMINAL_NEW, TT_STRING, "new", 0, -1 },
    // 245: optional_expr_245
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 321 },
    // 246: alternative_expr_246
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 322 },
    // 247: production_expr
    { NC_PRODUCTION, NT_EXPR, TT_UNDEF, 0, 1, 324 },
    // 248: alternative_expr_248
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 4, 325 },
    // 249: production_expr_list
    { NC_PRODUCTION, NT_EXPR_LIST, TT_UNDEF, 0, 1, 329 },
    // 250: mandatory_expr_250
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 330 },
    // 251: optional_repetitive_expr_251
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 332 },
    // 252: mandatory_expr_252
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 333 },
    // 253: production_call_arg
    { NC_PRODUCTION, NT_CALL_ARG, TT_UNDEF, 0, 1, 335 },
    // 254: mandatory_expr_254
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 336 },
    // 255: optional_expr_255
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 338 },
    // 256: mandatory_expr_256
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 339 },
    // 257: string_terminal_257
    { NC_TERMINAL, NT_TERMINAL_257, TT_STRING, "=>", 0, -1 },
    // 258: alternative_expr_258
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 341 },
    // 259: string_terminal_259
    { NC_TERMINAL, NT_TERMINAL_DEFAULT, TT_STRING, "default", 0, -1 },
    // 260: production_call_arg_list
    { NC_PRODUCTION, NT_CALL_ARG_LIST, TT_UNDEF, 0, 1, 343 },
    // 261: mandatory_expr_261
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 344 },
    // 262: optional_repetitive_expr_262
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 346 },
    // 263: mandatory_expr_263
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 347 },
    // 264: production_block
    { NC_PRODUCTION, NT_BLOCK, TT_UNDEF, 0, 1, 349 },
    // 265: mandatory_expr_265
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 350 },
    // 266: string_terminal_266
    { NC_TERMINAL, NT_TERMINAL_LBRACE, TT_STRING, "{", 0, -1 },
    // 267: optional_expr_267
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 353 },
    // 268: string_terminal_268
    { NC_TERMINAL, NT_TERMINAL_RBRACE, TT_STRING, "}", 0, -1 },
    // 269: production_optional_block
    { NC_PRODUCTION, NT_OPTIONAL_BLOCK, TT_UNDEF, 0, 1, 354 },
    // 270: alternative_expr_270
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 355 },
    // 271: string_terminal_271
    { NC_TERMINAL, NT_TERMINAL_SEMIC, TT_STRING, ";", 0, -1 },
    // 272: production_argument_decl
    { NC_PRODUCTION, NT_ARGUMENT_DECL, TT_UNDEF, 0, 1, 357 },
    // 273: alternative_expr_273
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 358 },
    // 274: mandatory_expr_274
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 4, 360 },
    // 275: string_terminal_275
    { NC_TERMINAL, NT_TERMINAL_COLON, TT_STRING, ":", 0, -1 },
    // 276: optional_expr_276
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 364 },
    // 277: mandatory_expr_277
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 365 },
    // 278: string_terminal_278
    { NC_TERMINAL, NT_TERMINAL_EQ, TT_STRING, "=", 0, -1 },
    // 279: string_terminal_279
    { NC_TERMINAL, NT_TERMINAL_ELLIPSIS, TT_STRING, "...", 0, -1 },
    // 280: production_argument_list
    { NC_PRODUCTION, NT_ARGUMENT_LIST, TT_UNDEF, 0, 1, 367 },
    // 281: mandatory_expr_281
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 368 },
    // 282: optional_repetitive_expr_282
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 370 },
    // 283: mandatory_expr_283
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 371 },
    // 284: string_terminal_284
    { NC_TERMINAL, NT_TERMINAL_SEMIC, TT_STRING, ";", 0, -1 },
    // 285: production_arg_declarator
    { NC_PRODUCTION, NT_ARG_DECLARATOR, TT_UNDEF, 0, 1, 373 },
    // 286: mandatory_expr_286
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 374 },
    // 287: optional_expr_287
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 377 },
    // 288: production_return_decl
    { NC_PRODUCTION, NT_RETURN_DECL, TT_UNDEF, 0, 1, 378 },
    // 289: mandatory_expr_289
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 379 },
    // 290: string_terminal_290
    { NC_TERMINAL, NT_TERMINAL_RETURNING, TT_STRING, "returning", 0, -1 },
    // 291: production_ident_list
    { NC_PRODUCTION, NT_IDENT_LIST, TT_UNDEF, 0, 1, 381 },
    // 292: mandatory_expr_292
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 382 },
    // 293: optional_repetitive_expr_293
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 384 },
    // 294: mandatory_expr_294
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 385 },
    // 295: production_extends_clause
    { NC_PRODUCTION, NT_EXTENDS_CLAUSE, TT_UNDEF, 0, 1, 387 },
    // 296: mandatory_expr_296
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 388 },
    // 297: string_terminal_297
    { NC_TERMINAL, NT_TERMINAL_EXTENDS, TT_STRING, "extends", 0, -1 },
    // 298: production_impl_clause
    { NC_PRODUCTION, NT_IMPL_CLAUSE, TT_UNDEF, 0, 1, 390 },
    // 299: mandatory_expr_299
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 391 },
    // 300: string_terminal_300
    { NC_TERMINAL, NT_TERMINAL_IMPLEMENTS, TT_STRING, "implements", 0, -1 },
    // 301: production_visibility
    { NC_PRODUCTION, NT_VISIBILITY, TT_UNDEF, 0, 1, 393 },
    // 302: alternative_expr_302
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 394 },
    // 303: string_terminal_303
    { NC_TERMINAL, NT_TERMINAL_PRIVATE, TT_STRING, "private", 0, -1 },
    // 304: string_terminal_304
    { NC_TERMINAL, NT_TERMINAL_PROTECTED, TT_STRING, "protected", 0, -1 },
    // 305: string_terminal_305
    { NC_TERMINAL, NT_TERMINAL_PUBLIC, TT_STRING, "public", 0, -1 },
    // 306: production_access_type
    { NC_PRODUCTION, NT_ACCESS_TYPE, TT_UNDEF, 0, 1, 397 },
    // 307: alternative_expr_307
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 398 },
    // 308: string_terminal_308
    { NC_TERMINAL, NT_TERMINAL_READONLY, TT_STRING, "readonly", 0, -1 },
    // 309: string_terminal_309
    { NC_TERMINAL, NT_TERMINAL_READWRITE, TT_STRING, "readwrite", 0, -1 },
    // 310: string_terminal_310
    { NC_TERMINAL, NT_TERMINAL_WRITEONLY, TT_STRING, "writeonly", 0, -1 },
    // 311: production_storage_type
    { NC_PRODUCTION, NT_STORAGE_TYPE, TT_UNDEF, 0, 1, 401 },
    // 312: string_terminal_312
    { NC_TERMINAL, NT_TERMINAL_STATIC, TT_STRING, "static", 0, -1 },
    // 313: production_derivation
    { NC_PRODUCTION, NT_DERIVATION, TT_UNDEF, 0, 1, 402 },
    // 314: alternative_expr_314
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 403 },
    // 315: string_terminal_315
    { NC_TERMINAL, NT_TERMINAL_OVERRIDE, TT_STRING, "override", 0, -1 },
    // 316: string_terminal_316
    { NC_TERMINAL, NT_TERMINAL_FINAL, TT_STRING, "final", 0, -1 },
    // 317: production_implementation
    { NC_PRODUCTION, NT_IMPLEMENTATION, TT_UNDEF, 0, 1, 405 },
    // 318: string_terminal_318
    { NC_TERMINAL, NT_TERMINAL_IMPLEMENTATION, TT_STRING, "implementation", 0, -1 },
    // 319: production_attrib_flag
    { NC_PRODUCTION, NT_ATTRIB_FLAG, TT_UNDEF, 0, 1, 406 },
    // 320: alternative_expr_320
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 5, 407 },
    // 321: production_attrib_flags
    { NC_PRODUCTION, NT_ATTRIB_FLAGS, TT_UNDEF, 0, 1, 412 },
    // 322: mandatory_expr_322
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 413 },
    // 323: optional_repetitive_expr_323
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 415 },
    // 324: production_attrib_decl
    { NC_PRODUCTION, NT_ATTRIB_DECL, TT_UNDEF, 0, 1, 416 },
    // 325: mandatory_expr_325
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 7, 417 },
    // 326: optional_expr_326
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 424 },
    // 327: string_terminal_327
    { NC_TERMINAL, NT_TERMINAL_ATTRIBUTE, TT_STRING, "attribute", 0, -1 },
    // 328: string_terminal_328
    { NC_TERMINAL, NT_TERMINAL_COLON, TT_STRING, ":", 0, -1 },
    // 329: optional_expr_329
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 425 },
    // 330: mandatory_expr_330
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 426 },
    // 331: production_method_flag
    { NC_PRODUCTION, NT_METHOD_FLAG, TT_UNDEF, 0, 1, 428 },
    // 332: alternative_expr_332
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 4, 429 },
    // 333: production_method_flags
    { NC_PRODUCTION, NT_METHOD_FLAGS, TT_UNDEF, 0, 1, 433 },
    // 334: mandatory_expr_334
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 434 },
    // 335: optional_repetitive_expr_335
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 436 },
    // 336: production_method_decl
    { NC_PRODUCTION, NT_METHOD_DECL, TT_UNDEF, 0, 1, 437 },
    // 337: mandatory_expr_337
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 6, 438 },
    // 338: optional_expr_338
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 444 },
    // 339: string_terminal_339
    { NC_TERMINAL, NT_TERMINAL_METHOD, TT_STRING, "method", 0, -1 },
    // 340: optional_expr_340
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 445 },
    // 341: production_field
    { NC_PRODUCTION, NT_FIELD, TT_UNDEF, 0, 1, 446 },
    // 342: alternative_expr_342
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 4, 447 },
    // 343: production_field_list
    { NC_PRODUCTION, NT_FIELD_LIST, TT_UNDEF, 0, 1, 451 },
    // 344: mandatory_expr_344
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 452 },
    // 345: optional_repetitive_expr_345
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 454 },
    // 346: production_class_decl
    { NC_PRODUCTION, NT_CLASS_DECL, TT_UNDEF, 0, 1, 455 },
    // 347: mandatory_expr_347
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 7, 456 },
    // 348: string_terminal_348
    { NC_TERMINAL, NT_TERMINAL_CLASS, TT_STRING, "class", 0, -1 },
    // 349: optional_expr_349
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 463 },
    // 350: optional_expr_350
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 464 },
    // 351: string_terminal_351
    { NC_TERMINAL, NT_TERMINAL_LBRACE, TT_STRING, "{", 0, -1 },
    // 352: optional_expr_352
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 465 },
    // 353: string_terminal_353
    { NC_TERMINAL, NT_TERMINAL_RBRACE, TT_STRING, "}", 0, -1 },
    // 354: production_iattrib_decl
    { NC_PRODUCTION, NT_IATTRIB_DECL, TT_UNDEF, 0, 1, 466 },
    // 355: mandatory_expr_355
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 6, 467 },
    // 356: optional_expr_356
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 473 },
    // 357: production_imethod_decl
    { NC_PRODUCTION, NT_IMETHOD_DECL, TT_UNDEF, 0, 1, 474 },
    // 358: mandatory_expr_358
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 5, 475 },
    // 359: optional_expr_359
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 480 },
    // 360: production_ifield
    { NC_PRODUCTION, NT_IFIELD, TT_UNDEF, 0, 1, 481 },
    // 361: alternative_expr_361
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 4, 482 },
    // 362: production_ifield_list
    { NC_PRODUCTION, NT_IFIELD_LIST, TT_UNDEF, 0, 1, 486 },
    // 363: mandatory_expr_363
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 487 },
    // 364: optional_repetitive_expr_364
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 489 },
    // 365: production_interface_decl
    { NC_PRODUCTION, NT_INTERFACE_DECL, TT_UNDEF, 0, 1, 490 },
    // 366: mandatory_expr_366
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 6, 491 },
    // 367: string_terminal_367
    { NC_TERMINAL, NT_TERMINAL_INTERFACE, TT_STRING, "interface", 0, -1 },
    // 368: optional_expr_368
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 497 },
    // 369: optional_expr_369
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 498 },
    // 370: production_func_decl
    { NC_PRODUCTION, NT_FUNC_DECL, TT_UNDEF, 0, 1, 499 },
    // 371: mandatory_expr_371
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 6, 500 },
    // 372: optional_expr_372
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 506 },
    // 373: string_terminal_373
    { NC_TERMINAL, NT_TERMINAL_FUNCTION, TT_STRING, "function", 0, -1 },
    // 374: production_proc_decl
    { NC_PRODUCTION, NT_PROC_DECL, TT_UNDEF, 0, 1, 507 },
    // 375: mandatory_expr_375
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 5, 508 },
    // 376: optional_expr_376
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 513 },
    // 377: string_terminal_377
    { NC_TERMINAL, NT_TERMINAL_PROCEDURE, TT_STRING, "procedure", 0, -1 },
    // 378: production_var_decl
    { NC_PRODUCTION, NT_VAR_DECL, TT_UNDEF, 0, 1, 514 },
    // 379: mandatory_expr_379
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 5, 515 },
    // 380: string_terminal_380
    { NC_TERMINAL, NT_TERMINAL_VAR, TT_STRING, "var", 0, -1 },
    // 381: production_const_decl
    { NC_PRODUCTION, NT_CONST_DECL, TT_UNDEF, 0, 1, 520 },
    // 382: mandatory_expr_382
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 5, 521 },
    // 383: string_terminal_383
    { NC_TERMINAL, NT_TERMINAL_CONST, TT_STRING, "const", 0, -1 },
    // 384: production_enum_item
    { NC_PRODUCTION, NT_ENUM_ITEM, TT_UNDEF, 0, 1, 526 },
    // 385: mandatory_expr_385
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 527 },
    // 386: optional_expr_386
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 529 },
    // 387: mandatory_expr_387
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 530 },
    // 388: production_enum_item_list
    { NC_PRODUCTION, NT_ENUM_ITEM_LIST, TT_UNDEF, 0, 1, 532 },
    // 389: mandatory_expr_389
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 533 },
    // 390: optional_repetitive_expr_390
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 536 },
    // 391: mandatory_expr_391
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 537 },
    // 392: optional_expr_392
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 539 },
    // 393: production_enum_decl
    { NC_PRODUCTION, NT_ENUM_DECL, TT_UNDEF, 0, 1, 540 },
    // 394: mandatory_expr_394
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 5, 541 },
    // 395: string_terminal_395
    { NC_TERMINAL, NT_TERMINAL_ENUM, TT_STRING, "enum", 0, -1 },
    // 396: production_let_stmt
    { NC_PRODUCTION, NT_LET_STMT, TT_UNDEF, 0, 1, 546 },
    // 397: mandatory_expr_397
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 5, 547 },
    // 398: string_terminal_398
    { NC_TERMINAL, NT_TERMINAL_LET, TT_STRING, "let", 0, -1 },
    // 399: production_decl_stmt
    { NC_PRODUCTION, NT_DECL_STMT, TT_UNDEF, 0, 1, 552 },
    // 400: alternative_expr_400
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 7, 553 },
    // 401: production_block_decl
    { NC_PRODUCTION, NT_BLOCK_DECL, TT_UNDEF, 0, 1, 560 },
    // 402: alternative_expr_402
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 561 },
    // 403: production_import_path
    { NC_PRODUCTION, NT_IMPORT_PATH, TT_UNDEF, 0, 1, 564 },
    // 404: mandatory_expr_404
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 565 },
    // 405: optional_repetitive_expr_405
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 567 },
    // 406: mandatory_expr_406
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 568 },
    // 407: production_import_list
    { NC_PRODUCTION, NT_IMPORT_LIST, TT_UNDEF, 0, 1, 570 },
    // 408: mandatory_expr_408
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 571 },
    // 409: optional_repetitive_expr_409
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 573 },
    // 410: mandatory_expr_410
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 574 },
    // 411: production_import_stmt
    { NC_PRODUCTION, NT_IMPORT_STMT, TT_UNDEF, 0, 1, 576 },
    // 412: mandatory_expr_412
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 577 },
    // 413: string_terminal_413
    { NC_TERMINAL, NT_TERMINAL_IMPORT, TT_STRING, "import", 0, -1 },
    // 414: production_xref_type
    { NC_PRODUCTION, NT_XREF_TYPE, TT_UNDEF, 0, 1, 580 },
    // 415: alternative_expr_415
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 581 },
    // 416: string_terminal_416
    { NC_TERMINAL, NT_TERMINAL_MODULE, TT_STRING, "module", 0, -1 },
    // 417: string_terminal_417
    { NC_TERMINAL, NT_TERMINAL_PACKAGE, TT_STRING, "package", 0, -1 },
    // 418: string_terminal_418
    { NC_TERMINAL, NT_TERMINAL_LIBRARY, TT_STRING, "library", 0, -1 },
    // 419: production_str_lit_list
    { NC_PRODUCTION, NT_STR_LIT_LIST, TT_UNDEF, 0, 1, 584 },
    // 420: mandatory_expr_420
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 585 },
    // 421: optional_repetitive_expr_421
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 587 },
    // 422: mandatory_expr_422
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 588 },
    // 423: production_platform_spec
    { NC_PRODUCTION, NT_PLATFORM_SPEC, TT_UNDEF, 0, 1, 590 },
    // 424: mandatory_expr_424
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 591 },
    // 425: string_terminal_425
    { NC_TERMINAL, NT_TERMINAL_PLATFORM, TT_STRING, "platform", 0, -1 },
    // 426: production_language_spec
    { NC_PRODUCTION, NT_LANGUAGE_SPEC, TT_UNDEF, 0, 1, 593 },
    // 427: mandatory_expr_427
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 594 },
    // 428: string_terminal_428
    { NC_TERMINAL, NT_TERMINAL_LANGUAGE, TT_STRING, "language", 0, -1 },
    // 429: production_header_spec
    { NC_PRODUCTION, NT_HEADER_SPEC, TT_UNDEF, 0, 1, 596 },
    // 430: mandatory_expr_430
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 597 },
    // 431: string_terminal_431
    { NC_TERMINAL, NT_TERMINAL_HEADER, TT_STRING, "header", 0, -1 },
    // 432: production_function_spec
    { NC_PRODUCTION, NT_FUNCTION_SPEC, TT_UNDEF, 0, 1, 599 },
    // 433: mandatory_expr_433
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 600 },
    // 434: production_procedure_spec
    { NC_PRODUCTION, NT_PROCEDURE_SPEC, TT_UNDEF, 0, 1, 602 },
    // 435: mandatory_expr_435
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 603 },
    // 436: production_class_spec
    { NC_PRODUCTION, NT_CLASS_SPEC, TT_UNDEF, 0, 1, 605 },
    // 437: mandatory_expr_437
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 606 },
    // 438: production_alien_spec
    { NC_PRODUCTION, NT_ALIEN_SPEC, TT_UNDEF, 0, 1, 608 },
    // 439: alternative_expr_439
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 6, 609 },
    // 440: production_alien_specs
    { NC_PRODUCTION, NT_ALIEN_SPECS, TT_UNDEF, 0, 1, 615 },
    // 441: mandatory_expr_441
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 616 },
    // 442: optional_repetitive_expr_442
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 618 },
    // 443: mandatory_expr_443
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 619 },
    // 444: production_alien_stmt
    { NC_PRODUCTION, NT_ALIEN_STMT, TT_UNDEF, 0, 1, 621 },
    // 445: mandatory_expr_445
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 5, 622 },
    // 446: string_terminal_446
    { NC_TERMINAL, NT_TERMINAL_ALIEN, TT_STRING, "alien", 0, -1 },
    // 447: optional_expr_447
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 627 },
    // 448: mandatory_expr_448
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 628 },
    // 449: production_global_stmt
    { NC_PRODUCTION, NT_GLOBAL_STMT, TT_UNDEF, 0, 1, 630 },
    // 450: production_global_stmts
    { NC_PRODUCTION, NT_GLOBAL_STMTS, TT_UNDEF, 0, 1, 631 },
    // 451: mandatory_expr_451
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 632 },
    // 452: optional_repetitive_expr_452
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 634 },
    // 453: production_global_intro
    { NC_PRODUCTION, NT_GLOBAL_INTRO, TT_UNDEF, 0, 1, 635 },
    // 454: alternative_expr_454
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 636 },
    // 455: production_global_spec
    { NC_PRODUCTION, NT_GLOBAL_SPEC, TT_UNDEF, 0, 1, 638 },
    // 456: mandatory_expr_456
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 639 },
    // 457: alternative_expr_457
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 642 },
    // 458: string_terminal_458
    { NC_TERMINAL, NT_TERMINAL_PROGRAM, TT_STRING, "program", 0, -1 },
    // 459: production_global_scope
    { NC_PRODUCTION, NT_GLOBAL_SCOPE, TT_UNDEF, 0, 1, 644 },
    // 460: mandatory_expr_460
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 645 },
    // 461: optional_expr_461
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 648 },
    // 462: optional_repetitive_expr_462
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 649 },
    // 463: optional_repetitive_expr_463
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 650 },
    // 464: production_label_decl
    { NC_PRODUCTION, NT_LABEL_DECL, TT_UNDEF, 0, 1, 651 },
    // 465: mandatory_expr_465
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 652 },
    // 466: production_call_stmt
    { NC_PRODUCTION, NT_CALL_STMT, TT_UNDEF, 0, 1, 654 },
    // 467: mandatory_expr_467
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 655 },
    // 468: string_terminal_468
    { NC_TERMINAL, NT_TERMINAL_CALL, TT_STRING, "call", 0, -1 },
    // 469: production_block_or_stmt
    { NC_PRODUCTION, NT_BLOCK_OR_STMT, TT_UNDEF, 0, 1, 658 },
    // 470: alternative_expr_470
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 659 },
    // 471: production_if_stmt
    { NC_PRODUCTION, NT_IF_STMT, TT_UNDEF, 0, 1, 661 },
    // 472: mandatory_expr_472
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 4, 662 },
    // 473: alternative_expr_473
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 666 },
    // 474: string_terminal_474
    { NC_TERMINAL, NT_TERMINAL_IF, TT_STRING, "if", 0, -1 },
    // 475: string_terminal_475
    { NC_TERMINAL, NT_TERMINAL_UNLESS, TT_STRING, "unless", 0, -1 },
    // 476: optional_expr_476
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 668 },
    // 477: mandatory_expr_477
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 669 },
    // 478: string_terminal_478
    { NC_TERMINAL, NT_TERMINAL_ELSE, TT_STRING, "else", 0, -1 },
    // 479: production_while_stmt
    { NC_PRODUCTION, NT_WHILE_STMT, TT_UNDEF, 0, 1, 671 },
    // 480: mandatory_expr_480
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 672 },
    // 481: alternative_expr_481
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 675 },
    // 482: string_terminal_482
    { NC_TERMINAL, NT_TERMINAL_WHILE, TT_STRING, "while", 0, -1 },
    // 483: string_terminal_483
    { NC_TERMINAL, NT_TERMINAL_UNTIL, TT_STRING, "until", 0, -1 },
    // 484: production_repeat_stmt
    { NC_PRODUCTION, NT_REPEAT_STMT, TT_UNDEF, 0, 1, 677 },
    // 485: mandatory_expr_485
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 5, 678 },
    // 486: alternative_expr_486
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 683 },
    // 487: string_terminal_487
    { NC_TERMINAL, NT_TERMINAL_REPEAT, TT_STRING, "repeat", 0, -1 },
    // 488: string_terminal_488
    { NC_TERMINAL, NT_TERMINAL_DO, TT_STRING, "do", 0, -1 },
    // 489: alternative_expr_489
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 685 },
    // 490: production_loop_stmt
    { NC_PRODUCTION, NT_LOOP_STMT, TT_UNDEF, 0, 1, 687 },
    // 491: mandatory_expr_491
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 688 },
    // 492: alternative_expr_492
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 690 },
    // 493: string_terminal_493
    { NC_TERMINAL, NT_TERMINAL_LOOP, TT_STRING, "loop", 0, -1 },
    // 494: string_terminal_494
    { NC_TERMINAL, NT_TERMINAL_FOREVER, TT_STRING, "forever", 0, -1 },
    // 495: production_for_stmt
    { NC_PRODUCTION, NT_FOR_STMT, TT_UNDEF, 0, 1, 692 },
    // 496: mandatory_expr_496
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 8, 693 },
    // 497: string_terminal_497
    { NC_TERMINAL, NT_TERMINAL_FOR, TT_STRING, "for", 0, -1 },
    // 498: alternative_expr_498
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 701 },
    // 499: string_terminal_499
    { NC_TERMINAL, NT_TERMINAL_TO, TT_STRING, "to", 0, -1 },
    // 500: string_terminal_500
    { NC_TERMINAL, NT_TERMINAL_DOWNTO, TT_STRING, "downto", 0, -1 },
    // 501: production_loop_control
    { NC_PRODUCTION, NT_LOOP_CONTROL, TT_UNDEF, 0, 1, 703 },
    // 502: mandatory_expr_502
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 704 },
    // 503: alternative_expr_503
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 707 },
    // 504: string_terminal_504
    { NC_TERMINAL, NT_TERMINAL_BREAK, TT_STRING, "break", 0, -1 },
    // 505: string_terminal_505
    { NC_TERMINAL, NT_TERMINAL_CONTINUE, TT_STRING, "continue", 0, -1 },
    // 506: string_terminal_506
    { NC_TERMINAL, NT_TERMINAL_AGAIN, TT_STRING, "again", 0, -1 },
    // 507: optional_expr_507
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 710 },
    // 508: production_loop_type_stmt
    { NC_PRODUCTION, NT_LOOP_TYPE_STMT, TT_UNDEF, 0, 1, 711 },
    // 509: alternative_expr_509
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 5, 712 },
    // 510: production_switch_case
    { NC_PRODUCTION, NT_SWITCH_CASE, TT_UNDEF, 0, 1, 717 },
    // 511: mandatory_expr_511
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 4, 718 },
    // 512: string_terminal_512
    { NC_TERMINAL, NT_TERMINAL_CASE, TT_STRING, "case", 0, -1 },
    // 513: production_default_case
    { NC_PRODUCTION, NT_DEFAULT_CASE, TT_UNDEF, 0, 1, 722 },
    // 514: mandatory_expr_514
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 723 },
    // 515: production_any_case
    { NC_PRODUCTION, NT_ANY_CASE, TT_UNDEF, 0, 1, 726 },
    // 516: alternative_expr_516
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 727 },
    // 517: production_case_list
    { NC_PRODUCTION, NT_CASE_LIST, TT_UNDEF, 0, 1, 729 },
    // 518: mandatory_expr_518
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 730 },
    // 519: optional_repetitive_expr_519
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 732 },
    // 520: production_switch_stmt
    { NC_PRODUCTION, NT_SWITCH_STMT, TT_UNDEF, 0, 1, 733 },
    // 521: mandatory_expr_521
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 5, 734 },
    // 522: string_terminal_522
    { NC_TERMINAL, NT_TERMINAL_SWITCH, TT_STRING, "switch", 0, -1 },
    // 523: production_goto_stmt
    { NC_PRODUCTION, NT_GOTO_STMT, TT_UNDEF, 0, 1, 739 },
    // 524: mandatory_expr_524
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 740 },
    // 525: alternative_expr_525
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 743 },
    // 526: string_terminal_526
    { NC_TERMINAL, NT_TERMINAL_GOTO, TT_STRING, "goto", 0, -1 },
    // 527: string_terminal_527
    { NC_TERMINAL, NT_TERMINAL_GOSUB, TT_STRING, "gosub", 0, -1 },
    // 528: production_return_stmt
    { NC_PRODUCTION, NT_RETURN_STMT, TT_UNDEF, 0, 1, 745 },
    // 529: mandatory_expr_529
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 746 },
    // 530: string_terminal_530
    { NC_TERMINAL, NT_TERMINAL_RETURN, TT_STRING, "return", 0, -1 },
    // 531: production_resultis_stmt
    { NC_PRODUCTION, NT_RESULTIS_STMT, TT_UNDEF, 0, 1, 748 },
    // 532: mandatory_expr_532
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 749 },
    // 533: string_terminal_533
    { NC_TERMINAL, NT_TERMINAL_RESULTIS, TT_STRING, "resultis", 0, -1 },
    // 534: production_delete_stmt
    { NC_PRODUCTION, NT_DELETE_STMT, TT_UNDEF, 0, 1, 752 },
    // 535: mandatory_expr_535
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 753 },
    // 536: string_terminal_536
    { NC_TERMINAL, NT_TERMINAL_DELETE, TT_STRING, "delete", 0, -1 },
    // 537: production_flow_ctrl_stmt
    { NC_PRODUCTION, NT_FLOW_CTRL_STMT, TT_UNDEF, 0, 1, 756 },
    // 538: alternative_expr_538
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 8, 757 },
    // 539: production_stmt
    { NC_PRODUCTION, NT_STMT, TT_UNDEF, 0, 1, 765 },
    // 540: alternative_expr_540
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 766 },
    // 541: production_statement
    { NC_PRODUCTION, NT_STATEMENT, TT_UNDEF, 0, 1, 769 },
    // 542: mandatory_expr_542
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 770 },
    // 543: optional_expr_543
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 772 },
    // 544: production_statement_list
    { NC_PRODUCTION, NT_STATEMENT_LIST, TT_UNDEF, 0, 1, 773 },
    // 545: mandatory_expr_545
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 774 },
    // 546: optional_repetitive_expr_546
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 776 },
};

