// code auto-generated by ebnfcomp; do not modify!
// (code might get overwritten during next ebnfcomp invocation)

#include <stddef.h>

typedef enum _nodeclass_t {
    NC_TERMINAL,
    NC_PRODUCTION,
    NC_MANDATORY,
    NC_ALTERNATIVE,
    NC_OPTIONAL,
    NC_OPTIONAL_REPETITIVE,
} nodeclass_t;

typedef enum _terminaltype_t {
    TT_UNDEF,
    TT_STRING,
    TT_REGEX,
} terminaltype_t;

typedef enum _nodetype_t {
    _NT_GENERIC,
    NT_INT_LIT,
    NT_TERMINAL_1,
    NT_REAL_LIT,
    NT_TERMINAL_4,
    NT_TERMINAL_7,
    NT_TERMINAL_9,
    NT_STR_LIT,
    NT_TERMINAL_11,
    NT_BOOL_LIT,
    NT_TERMINAL_14,
    NT_TERMINAL_15,
    NT_PTR_LIT,
    NT_TERMINAL_17,
    NT_IDENTIFIER,
    NT_TERMINAL_19,
    NT_BASE_TYPE,
    NT_TERMINAL_22,
    NT_TERMINAL_23,
    NT_TERMINAL_24,
    NT_TERMINAL_25,
    NT_TERMINAL_26,
    NT_OBJECT_POINTER,
    NT_TERMINAL_29,
    NT_CELL_TYPE,
    NT_CELL_POINTER,
    NT_TERMINAL_34,
    NT_TYPE,
    NT_TYPE_LIST,
    NT_TERMINAL_41,
    NT_NEG_OP,
    NT_TERMINAL_44,
    NT_TERMINAL_45,
    NT_MULT_OP,
    NT_TERMINAL_48,
    NT_TERMINAL_49,
    NT_ADD_OP,
    NT_TERMINAL_52,
    NT_SHF_OP,
    NT_TERMINAL_55,
    NT_TERMINAL_56,
    NT_CMP_OP,
    NT_TERMINAL_59,
    NT_TERMINAL_60,
    NT_TERMINAL_61,
    NT_TERMINAL_62,
    NT_TERMINAL_63,
    NT_TERMINAL_64,
    NT_AND_OP,
    NT_TERMINAL_66,
    NT_OR_OP,
    NT_TERMINAL_69,
    NT_TERMINAL_70,
    NT_C_NUM_BASE_E,
    NT_TERMINAL_74,
    NT_TERMINAL_75,
    NT_C_NUM_NEG_E,
    NT_C_NUM_MULT_E,
    NT_C_NUM_ADD_E,
    NT_C_NUM_SHF_E,
    NT_C_NUM_CMP_E,
    NT_C_NUM_AND_E,
    NT_C_NUM_OR_E,
    NT_C_NUM_E,
    NT_C_STR_BASE_E,
    NT_C_STR_ADD_E,
    NT_TERMINAL_110,
    NT_C_STR_CMP_E,
    NT_C_STR_AND_E,
    NT_C_STR_OR_E,
    NT_C_STR_E,
    NT_C_BOOL_BASE_E,
    NT_C_BOOL_NOT_E,
    NT_TERMINAL_129,
    NT_C_BOOL_AND_E,
    NT_C_BOOL_OR_E,
    NT_C_BOOL_E,
    NT_C_PTR_E,
    NT_CONST_EXPR,
    NT_C_EXPR_LIST,
    NT_TERMINAL_146,
    NT_ACCESS_OP,
    NT_TERMINAL_150,
    NT_TERMINAL_152,
    NT_TERMINAL_153,
    NT_IDENT_ACCESS,
    NT_TERMINAL_159,
    NT_TERMINAL_161,
    NT_VALOF_EXPR,
    NT_TERMINAL_164,
    NT_NUM_BASE_E,
    NT_NUM_NEG_E,
    NT_NUM_MULT_E,
    NT_NUM_ADD_E,
    NT_NUM_SHF_E,
    NT_NUM_CMP_E,
    NT_NUM_AND_E,
    NT_NUM_OR_E,
    NT_NUM_E,
    NT_STR_BASE_E,
    NT_STR_ADD_E,
    NT_STR_CMP_E,
    NT_STR_AND_E,
    NT_STR_OR_E,
    NT_STR_E,
    NT_BOOL_BASE_E,
    NT_BOOL_NOT_E,
    NT_BOOL_AND_E,
    NT_BOOL_OR_E,
    NT_BOOL_E,
    NT_ARRAY_INST,
    NT_TERMINAL_232,
    NT_TERMINAL_233,
    NT_OBJECT_INST,
    NT_PTR_E,
    NT_TERMINAL_240,
    NT_EXPR,
    NT_EXPR_LIST,
    NT_CALL_ARG,
    NT_TERMINAL_253,
    NT_TERMINAL_255,
    NT_CALL_ARG_LIST,
    NT_BLOCK,
    NT_TERMINAL_262,
    NT_TERMINAL_264,
    NT_OPTIONAL_BLOCK,
    NT_TERMINAL_267,
    NT_ARGUMENT_DECL,
    NT_TERMINAL_271,
    NT_TERMINAL_274,
    NT_TERMINAL_275,
    NT_ARGUMENT_LIST,
    NT_TERMINAL_280,
    NT_ARG_DECLARATOR,
    NT_RETURN_DECL,
    NT_TERMINAL_286,
    NT_IDENT_LIST,
    NT_EXTENDS_CLAUSE,
    NT_TERMINAL_293,
    NT_IMPL_CLAUSE,
    NT_TERMINAL_296,
    NT_VISIBILITY,
    NT_TERMINAL_299,
    NT_TERMINAL_300,
    NT_TERMINAL_301,
    NT_ACCESS_TYPE,
    NT_TERMINAL_304,
    NT_TERMINAL_305,
    NT_TERMINAL_306,
    NT_STORAGE_TYPE,
    NT_TERMINAL_308,
    NT_DERIVATION,
    NT_TERMINAL_311,
    NT_TERMINAL_312,
    NT_IMPLEMENTATION,
    NT_TERMINAL_314,
    NT_ATTRIB_FLAG,
    NT_ATTRIB_FLAGS,
    NT_ATTRIB_DECL,
    NT_TERMINAL_323,
    NT_TERMINAL_324,
    NT_METHOD_FLAG,
    NT_METHOD_FLAGS,
    NT_METHOD_DECL,
    NT_TERMINAL_335,
    NT_FIELD,
    NT_FIELD_LIST,
    NT_CLASS_DECL,
    NT_TERMINAL_344,
    NT_TERMINAL_347,
    NT_TERMINAL_349,
    NT_IATTRIB_DECL,
    NT_IMETHOD_DECL,
    NT_IFIELD,
    NT_IFIELD_LIST,
    NT_INTERFACE_DECL,
    NT_TERMINAL_363,
    NT_FUNC_DECL,
    NT_TERMINAL_369,
    NT_PROC_DECL,
    NT_TERMINAL_373,
    NT_VAR_DECL,
    NT_TERMINAL_376,
    NT_CONST_DECL,
    NT_TERMINAL_379,
    NT_ENUM_ITEM,
    NT_ENUM_ITEM_LIST,
    NT_ENUM_DECL,
    NT_TERMINAL_391,
    NT_LET_STMT,
    NT_TERMINAL_394,
    NT_DECL_STMT,
    NT_BLOCK_DECL,
    NT_IMPORT_PATH,
    NT_IMPORT_LIST,
    NT_IMPORT_STMT,
    NT_TERMINAL_409,
    NT_XREF_TYPE,
    NT_TERMINAL_412,
    NT_TERMINAL_413,
    NT_TERMINAL_414,
    NT_STR_LIT_LIST,
    NT_PLATFORM_SPEC,
    NT_TERMINAL_421,
    NT_LANGUAGE_SPEC,
    NT_TERMINAL_424,
    NT_HEADER_SPEC,
    NT_TERMINAL_427,
    NT_FUNCTION_SPEC,
    NT_PROCEDURE_SPEC,
    NT_CLASS_SPEC,
    NT_ALIEN_SPEC,
    NT_ALIEN_SPECS,
    NT_ALIEN_STMT,
    NT_TERMINAL_442,
    NT_GLOBAL_STMT,
    NT_GLOBAL_STMTS,
    NT_GLOBAL_INTRO,
    NT_GLOBAL_SPEC,
    NT_TERMINAL_454,
    NT_GLOBAL_SCOPE,
    NT_LABEL_DECL,
    NT_CALL_STMT,
    NT_TERMINAL_464,
    NT_END,
    NT_BLOCK_OR_STMT,
    NT_IF_STMT,
    NT_TERMINAL_472,
    NT_TERMINAL_473,
    NT_TERMINAL_476,
    NT_WHILE_STMT,
    NT_TERMINAL_480,
    NT_TERMINAL_481,
    NT_REPEAT_STMT,
    NT_TERMINAL_485,
    NT_TERMINAL_486,
    NT_LOOP_STMT,
    NT_TERMINAL_491,
    NT_TERMINAL_492,
    NT_FOR_STMT,
    NT_TERMINAL_495,
    NT_TERMINAL_497,
    NT_TERMINAL_498,
    NT_LOOP_CONTROL,
    NT_TERMINAL_502,
    NT_TERMINAL_503,
    NT_TERMINAL_504,
    NT_LOOP_TYPE_STMT,
    NT_SWITCH_CASE,
    NT_TERMINAL_510,
    NT_DEFAULT_CASE,
    NT_ANY_CASE,
    NT_CASE_LIST,
    NT_SWITCH_STMT,
    NT_TERMINAL_520,
    NT_GOTO_STMT,
    NT_TERMINAL_524,
    NT_TERMINAL_525,
    NT_RETURN_STMT,
    NT_TERMINAL_528,
    NT_RESULTIS_STMT,
    NT_TERMINAL_531,
    NT_DELETE_STMT,
    NT_TERMINAL_534,
    NT_FLOW_CTRL_STMT,
    NT_STMT,
    NT_STATEMENT,
    NT_STATEMENT_LIST,
} nodetype_t;

typedef struct _parsingnode_t {
    nodeclass_t        nodeClass;
    nodetype_t         nodeType;
    terminaltype_t     termType;
    const char*        text;
    size_t             numBranches;
    int                branches;
} parsingnode_t;

// branches

static const int branches[773] = {
    // 0: production_int_lit branches
    1, 
    // 1: production_real_lit branches
    3, 
    // 2: mandatory_expr_3 branches
    0, 4, 0, 5, 
    // 6: optional_expr_5 branches
    6, 
    // 7: mandatory_expr_6 branches
    7, 8, 0, 
    // 10: optional_expr_8 branches
    9, 
    // 11: production_str_lit branches
    11, 
    // 12: production_bool_lit branches
    13, 
    // 13: alternative_expr_13 branches
    14, 15, 
    // 15: production_ptr_lit branches
    17, 
    // 16: production_identifier branches
    19, 
    // 17: production_base_type branches
    21, 
    // 18: alternative_expr_21 branches
    22, 23, 24, 25, 26, 
    // 23: production_object_pointer branches
    28, 
    // 24: mandatory_expr_28 branches
    18, 29, 
    // 26: production_cell_type branches
    31, 
    // 27: alternative_expr_31 branches
    20, 27, 
    // 29: production_cell_pointer branches
    33, 
    // 30: mandatory_expr_33 branches
    30, 34, 
    // 32: production_type branches
    36, 
    // 33: alternative_expr_36 branches
    32, 27, 20, 
    // 36: production_type_list branches
    38, 
    // 37: mandatory_expr_38 branches
    35, 39, 
    // 39: optional_repetitive_expr_39 branches
    40, 
    // 40: mandatory_expr_40 branches
    41, 35, 
    // 42: production_neg_op branches
    43, 
    // 43: alternative_expr_43 branches
    44, 45, 
    // 45: production_mult_op branches
    47, 
    // 46: alternative_expr_47 branches
    34, 48, 49, 
    // 49: production_add_op branches
    51, 
    // 50: alternative_expr_51 branches
    52, 9, 
    // 52: production_shf_op branches
    54, 
    // 53: alternative_expr_54 branches
    55, 56, 
    // 55: production_cmp_op branches
    58, 
    // 56: alternative_expr_58 branches
    59, 60, 61, 62, 63, 64, 
    // 62: production_and_op branches
    66, 
    // 63: production_or_op branches
    68, 
    // 64: alternative_expr_68 branches
    69, 70, 
    // 66: production_c_num_base_e branches
    72, 
    // 67: alternative_expr_72 branches
    2, 0, 73, 18, 
    // 71: mandatory_expr_73 branches
    74, 140, 75, 
    // 74: production_c_num_neg_e branches
    77, 
    // 75: mandatory_expr_77 branches
    78, 71, 
    // 77: optional_expr_78 branches
    42, 
    // 78: production_c_num_mult_e branches
    80, 
    // 79: mandatory_expr_80 branches
    76, 81, 
    // 81: optional_repetitive_expr_81 branches
    82, 
    // 82: mandatory_expr_82 branches
    46, 76, 
    // 84: production_c_num_add_e branches
    84, 
    // 85: mandatory_expr_84 branches
    79, 85, 
    // 87: optional_repetitive_expr_85 branches
    86, 
    // 88: mandatory_expr_86 branches
    50, 79, 
    // 90: production_c_num_shf_e branches
    88, 
    // 91: mandatory_expr_88 branches
    83, 89, 
    // 93: optional_expr_89 branches
    90, 
    // 94: mandatory_expr_90 branches
    53, 83, 
    // 96: production_c_num_cmp_e branches
    92, 
    // 97: mandatory_expr_92 branches
    87, 93, 
    // 99: optional_expr_93 branches
    94, 
    // 100: mandatory_expr_94 branches
    57, 87, 
    // 102: production_c_num_and_e branches
    96, 
    // 103: mandatory_expr_96 branches
    91, 97, 
    // 105: optional_repetitive_expr_97 branches
    98, 
    // 106: mandatory_expr_98 branches
    65, 91, 
    // 108: production_c_num_or_e branches
    100, 
    // 109: mandatory_expr_100 branches
    95, 101, 
    // 111: optional_repetitive_expr_101 branches
    102, 
    // 112: mandatory_expr_102 branches
    67, 95, 
    // 114: production_c_num_e branches
    99, 
    // 115: production_c_str_base_e branches
    105, 
    // 116: alternative_expr_105 branches
    10, 18, 
    // 118: production_c_str_add_e branches
    107, 
    // 119: mandatory_expr_107 branches
    196, 108, 
    // 121: optional_repetitive_expr_108 branches
    109, 
    // 122: mandatory_expr_109 branches
    110, 196, 
    // 124: production_c_str_cmp_e branches
    112, 
    // 125: mandatory_expr_112 branches
    106, 113, 
    // 127: optional_expr_113 branches
    114, 
    // 128: mandatory_expr_114 branches
    57, 106, 
    // 130: production_c_str_and_e branches
    116, 
    // 131: mandatory_expr_116 branches
    111, 117, 
    // 133: optional_repetitive_expr_117 branches
    118, 
    // 134: mandatory_expr_118 branches
    65, 111, 
    // 136: production_c_str_or_e branches
    120, 
    // 137: mandatory_expr_120 branches
    119, 121, 
    // 139: optional_repetitive_expr_121 branches
    122, 
    // 140: mandatory_expr_122 branches
    67, 119, 
    // 142: production_c_str_e branches
    119, 
    // 143: production_c_bool_base_e branches
    125, 
    // 144: alternative_expr_125 branches
    12, 18, 
    // 146: production_c_bool_not_e branches
    127, 
    // 147: mandatory_expr_127 branches
    128, 124, 
    // 149: optional_expr_128 branches
    129, 
    // 150: production_c_bool_and_e branches
    131, 
    // 151: mandatory_expr_131 branches
    126, 132, 
    // 153: optional_repetitive_expr_132 branches
    133, 
    // 154: mandatory_expr_133 branches
    65, 126, 
    // 156: production_c_bool_or_e branches
    135, 
    // 157: mandatory_expr_135 branches
    130, 136, 
    // 159: optional_repetitive_expr_136 branches
    137, 
    // 160: mandatory_expr_137 branches
    67, 130, 
    // 162: production_c_bool_e branches
    134, 
    // 163: production_c_ptr_e branches
    16, 
    // 164: production_const_expr branches
    141, 
    // 165: alternative_expr_141 branches
    103, 123, 138, 139, 
    // 169: production_c_expr_list branches
    143, 
    // 170: mandatory_expr_143 branches
    140, 144, 
    // 172: optional_repetitive_expr_144 branches
    145, 
    // 173: mandatory_expr_145 branches
    146, 140, 
    // 175: production_access_op branches
    148, 
    // 176: alternative_expr_148 branches
    149, 151, 
    // 178: mandatory_expr_149 branches
    150, 18, 
    // 180: mandatory_expr_151 branches
    152, 243, 153, 
    // 183: production_ident_access branches
    155, 
    // 184: mandatory_expr_155 branches
    18, 156, 157, 
    // 187: optional_repetitive_expr_156 branches
    147, 
    // 188: optional_expr_157 branches
    158, 
    // 189: mandatory_expr_158 branches
    159, 160, 161, 
    // 192: optional_expr_160 branches
    256, 
    // 193: production_valof_expr branches
    163, 
    // 194: mandatory_expr_163 branches
    164, 35, 260, 
    // 197: production_num_base_e branches
    166, 
    // 198: alternative_expr_166 branches
    2, 0, 167, 154, 162, 
    // 203: mandatory_expr_167 branches
    74, 243, 75, 
    // 206: production_num_neg_e branches
    169, 
    // 207: mandatory_expr_169 branches
    170, 165, 
    // 209: optional_expr_170 branches
    42, 
    // 210: production_num_mult_e branches
    172, 
    // 211: mandatory_expr_172 branches
    168, 173, 
    // 213: optional_repetitive_expr_173 branches
    174, 
    // 214: mandatory_expr_174 branches
    46, 168, 
    // 216: production_num_add_e branches
    176, 
    // 217: mandatory_expr_176 branches
    171, 177, 
    // 219: optional_repetitive_expr_177 branches
    178, 
    // 220: mandatory_expr_178 branches
    50, 171, 
    // 222: production_num_shf_e branches
    180, 
    // 223: mandatory_expr_180 branches
    175, 181, 
    // 225: optional_expr_181 branches
    182, 
    // 226: mandatory_expr_182 branches
    53, 175, 
    // 228: production_num_cmp_e branches
    184, 
    // 229: mandatory_expr_184 branches
    179, 185, 
    // 231: optional_expr_185 branches
    186, 
    // 232: mandatory_expr_186 branches
    57, 179, 
    // 234: production_num_and_e branches
    188, 
    // 235: mandatory_expr_188 branches
    183, 189, 
    // 237: optional_repetitive_expr_189 branches
    190, 
    // 238: mandatory_expr_190 branches
    65, 183, 
    // 240: production_num_or_e branches
    192, 
    // 241: mandatory_expr_192 branches
    187, 193, 
    // 243: optional_repetitive_expr_193 branches
    194, 
    // 244: mandatory_expr_194 branches
    67, 187, 
    // 246: production_num_e branches
    191, 
    // 247: production_str_base_e branches
    197, 
    // 248: alternative_expr_197 branches
    10, 154, 162, 
    // 251: production_str_add_e branches
    199, 
    // 252: mandatory_expr_199 branches
    196, 200, 
    // 254: optional_repetitive_expr_200 branches
    201, 
    // 255: mandatory_expr_201 branches
    52, 196, 
    // 257: production_str_cmp_e branches
    203, 
    // 258: mandatory_expr_203 branches
    198, 204, 
    // 260: optional_expr_204 branches
    205, 
    // 261: mandatory_expr_205 branches
    57, 198, 
    // 263: production_str_and_e branches
    207, 
    // 264: mandatory_expr_207 branches
    202, 208, 
    // 266: optional_repetitive_expr_208 branches
    209, 
    // 267: mandatory_expr_209 branches
    65, 202, 
    // 269: production_str_or_e branches
    211, 
    // 270: mandatory_expr_211 branches
    210, 212, 
    // 272: optional_repetitive_expr_212 branches
    213, 
    // 273: mandatory_expr_213 branches
    67, 210, 
    // 275: production_str_e branches
    210, 
    // 276: production_bool_base_e branches
    216, 
    // 277: alternative_expr_216 branches
    12, 154, 162, 
    // 280: production_bool_not_e branches
    218, 
    // 281: mandatory_expr_218 branches
    219, 215, 
    // 283: optional_expr_219 branches
    45, 
    // 284: production_bool_and_e branches
    221, 
    // 285: mandatory_expr_221 branches
    217, 222, 
    // 287: optional_repetitive_expr_222 branches
    223, 
    // 288: mandatory_expr_223 branches
    65, 217, 
    // 290: production_bool_or_e branches
    225, 
    // 291: mandatory_expr_225 branches
    220, 226, 
    // 293: optional_repetitive_expr_226 branches
    227, 
    // 294: mandatory_expr_227 branches
    67, 220, 
    // 296: production_bool_e branches
    224, 
    // 297: production_array_inst branches
    230, 
    // 298: mandatory_expr_230 branches
    152, 231, 153, 
    // 301: alternative_expr_231 branches
    232, 233, 195, 
    // 304: production_object_inst branches
    235, 
    // 305: mandatory_expr_235 branches
    74, 236, 75, 
    // 308: optional_expr_236 branches
    245, 
    // 309: production_ptr_e branches
    238, 
    // 310: alternative_expr_238 branches
    239, 16, 
    // 312: mandatory_expr_239 branches
    240, 35, 241, 
    // 315: optional_expr_241 branches
    242, 
    // 316: alternative_expr_242 branches
    229, 234, 
    // 318: production_expr branches
    244, 
    // 319: alternative_expr_244 branches
    195, 214, 228, 237, 
    // 323: production_expr_list branches
    246, 
    // 324: mandatory_expr_246 branches
    243, 247, 
    // 326: optional_repetitive_expr_247 branches
    248, 
    // 327: mandatory_expr_248 branches
    41, 243, 
    // 329: production_call_arg branches
    250, 
    // 330: mandatory_expr_250 branches
    251, 254, 
    // 332: optional_expr_251 branches
    252, 
    // 333: mandatory_expr_252 branches
    18, 253, 
    // 335: alternative_expr_254 branches
    255, 243, 
    // 337: production_call_arg_list branches
    257, 
    // 338: mandatory_expr_257 branches
    249, 258, 
    // 340: optional_repetitive_expr_258 branches
    259, 
    // 341: mandatory_expr_259 branches
    41, 249, 
    // 343: production_block branches
    261, 
    // 344: mandatory_expr_261 branches
    262, 263, 264, 
    // 347: optional_expr_263 branches
    542, 
    // 348: production_optional_block branches
    266, 
    // 349: alternative_expr_266 branches
    260, 267, 
    // 351: production_argument_decl branches
    269, 
    // 352: alternative_expr_269 branches
    270, 275, 
    // 354: mandatory_expr_270 branches
    287, 271, 35, 272, 
    // 358: optional_expr_272 branches
    273, 
    // 359: mandatory_expr_273 branches
    274, 142, 
    // 361: production_argument_list branches
    277, 
    // 362: mandatory_expr_277 branches
    268, 278, 
    // 364: optional_repetitive_expr_278 branches
    279, 
    // 365: mandatory_expr_279 branches
    280, 268, 
    // 367: production_arg_declarator branches
    282, 
    // 368: mandatory_expr_282 branches
    74, 283, 75, 
    // 371: optional_expr_283 branches
    276, 
    // 372: production_return_decl branches
    285, 
    // 373: mandatory_expr_285 branches
    286, 37, 
    // 375: production_ident_list branches
    288, 
    // 376: mandatory_expr_288 branches
    18, 289, 
    // 378: optional_repetitive_expr_289 branches
    290, 
    // 379: mandatory_expr_290 branches
    41, 18, 
    // 381: production_extends_clause branches
    292, 
    // 382: mandatory_expr_292 branches
    293, 287, 
    // 384: production_impl_clause branches
    295, 
    // 385: mandatory_expr_295 branches
    296, 287, 
    // 387: production_visibility branches
    298, 
    // 388: alternative_expr_298 branches
    299, 300, 301, 
    // 391: production_access_type branches
    303, 
    // 392: alternative_expr_303 branches
    304, 305, 306, 
    // 395: production_storage_type branches
    308, 
    // 396: production_derivation branches
    310, 
    // 397: alternative_expr_310 branches
    311, 312, 
    // 399: production_implementation branches
    314, 
    // 400: production_attrib_flag branches
    316, 
    // 401: alternative_expr_316 branches
    297, 302, 307, 309, 313, 
    // 406: production_attrib_flags branches
    318, 
    // 407: mandatory_expr_318 branches
    315, 319, 
    // 409: optional_repetitive_expr_319 branches
    315, 
    // 410: production_attrib_decl branches
    321, 
    // 411: mandatory_expr_321 branches
    322, 323, 287, 324, 35, 325, 267, 
    // 418: optional_expr_322 branches
    317, 
    // 419: optional_expr_325 branches
    326, 
    // 420: mandatory_expr_326 branches
    59, 142, 
    // 422: production_method_flag branches
    328, 
    // 423: alternative_expr_328 branches
    297, 307, 309, 313, 
    // 427: production_method_flags branches
    330, 
    // 428: mandatory_expr_330 branches
    327, 331, 
    // 430: optional_repetitive_expr_331 branches
    327, 
    // 431: production_method_decl branches
    333, 
    // 432: mandatory_expr_333 branches
    334, 335, 18, 281, 336, 265, 
    // 438: optional_expr_334 branches
    329, 
    // 439: optional_expr_336 branches
    284, 
    // 440: production_field branches
    338, 
    // 441: alternative_expr_338 branches
    320, 332, 377, 389, 
    // 445: production_field_list branches
    340, 
    // 446: mandatory_expr_340 branches
    337, 341, 
    // 448: optional_repetitive_expr_341 branches
    337, 
    // 449: production_class_decl branches
    343, 
    // 450: mandatory_expr_343 branches
    344, 18, 345, 346, 347, 348, 349, 
    // 457: optional_expr_345 branches
    291, 
    // 458: optional_expr_346 branches
    294, 
    // 459: optional_expr_348 branches
    339, 
    // 460: production_iattrib_decl branches
    351, 
    // 461: mandatory_expr_351 branches
    352, 323, 287, 271, 35, 267, 
    // 467: optional_expr_352 branches
    302, 
    // 468: production_imethod_decl branches
    354, 
    // 469: mandatory_expr_354 branches
    335, 18, 281, 355, 267, 
    // 474: optional_expr_355 branches
    284, 
    // 475: production_ifield branches
    357, 
    // 476: alternative_expr_357 branches
    350, 353, 377, 389, 
    // 480: production_ifield_list branches
    359, 
    // 481: mandatory_expr_359 branches
    356, 360, 
    // 483: optional_repetitive_expr_360 branches
    356, 
    // 484: production_interface_decl branches
    362, 
    // 485: mandatory_expr_362 branches
    363, 18, 364, 262, 365, 264, 
    // 491: optional_expr_364 branches
    291, 
    // 492: optional_expr_365 branches
    358, 
    // 493: production_func_decl branches
    367, 
    // 494: mandatory_expr_367 branches
    368, 369, 18, 281, 284, 265, 
    // 500: optional_expr_368 branches
    297, 
    // 501: production_proc_decl branches
    371, 
    // 502: mandatory_expr_371 branches
    372, 373, 18, 281, 265, 
    // 507: optional_expr_372 branches
    297, 
    // 508: production_var_decl branches
    375, 
    // 509: mandatory_expr_375 branches
    376, 287, 271, 35, 267, 
    // 514: production_const_decl branches
    378, 
    // 515: mandatory_expr_378 branches
    379, 287, 59, 142, 267, 
    // 520: production_enum_item branches
    381, 
    // 521: mandatory_expr_381 branches
    18, 382, 
    // 523: optional_expr_382 branches
    383, 
    // 524: mandatory_expr_383 branches
    59, 140, 
    // 526: production_enum_item_list branches
    385, 
    // 527: mandatory_expr_385 branches
    380, 386, 388, 
    // 530: optional_repetitive_expr_386 branches
    387, 
    // 531: mandatory_expr_387 branches
    41, 380, 
    // 533: optional_expr_388 branches
    41, 
    // 534: production_enum_decl branches
    390, 
    // 535: mandatory_expr_390 branches
    391, 18, 262, 384, 264, 
    // 540: production_let_stmt branches
    393, 
    // 541: mandatory_expr_393 branches
    394, 287, 59, 245, 267, 
    // 546: production_decl_stmt branches
    396, 
    // 547: alternative_expr_396 branches
    342, 361, 377, 389, 366, 370, 374, 
    // 554: production_block_decl branches
    398, 
    // 555: alternative_expr_398 branches
    377, 389, 374, 
    // 558: production_import_path branches
    400, 
    // 559: mandatory_expr_400 branches
    18, 401, 
    // 561: optional_repetitive_expr_401 branches
    402, 
    // 562: mandatory_expr_402 branches
    48, 18, 
    // 564: production_import_list branches
    404, 
    // 565: mandatory_expr_404 branches
    399, 405, 
    // 567: optional_repetitive_expr_405 branches
    406, 
    // 568: mandatory_expr_406 branches
    41, 399, 
    // 570: production_import_stmt branches
    408, 
    // 571: mandatory_expr_408 branches
    409, 399, 267, 
    // 574: production_xref_type branches
    411, 
    // 575: alternative_expr_411 branches
    412, 413, 414, 
    // 578: production_str_lit_list branches
    416, 
    // 579: mandatory_expr_416 branches
    10, 417, 
    // 581: optional_repetitive_expr_417 branches
    418, 
    // 582: mandatory_expr_418 branches
    41, 10, 
    // 584: production_platform_spec branches
    420, 
    // 585: mandatory_expr_420 branches
    421, 415, 
    // 587: production_language_spec branches
    423, 
    // 588: mandatory_expr_423 branches
    424, 415, 
    // 590: production_header_spec branches
    426, 
    // 591: mandatory_expr_426 branches
    427, 415, 
    // 593: production_function_spec branches
    429, 
    // 594: mandatory_expr_429 branches
    369, 415, 
    // 596: production_procedure_spec branches
    431, 
    // 597: mandatory_expr_431 branches
    373, 415, 
    // 599: production_class_spec branches
    433, 
    // 600: mandatory_expr_433 branches
    344, 415, 
    // 602: production_alien_spec branches
    435, 
    // 603: alternative_expr_435 branches
    419, 422, 425, 428, 430, 432, 
    // 609: production_alien_specs branches
    437, 
    // 610: mandatory_expr_437 branches
    434, 438, 
    // 612: optional_repetitive_expr_438 branches
    439, 
    // 613: mandatory_expr_439 branches
    41, 434, 
    // 615: production_alien_stmt branches
    441, 
    // 616: mandatory_expr_441 branches
    442, 410, 18, 443, 267, 
    // 621: optional_expr_443 branches
    444, 
    // 622: mandatory_expr_444 branches
    41, 436, 
    // 624: production_global_stmt branches
    395, 
    // 625: production_global_stmts branches
    447, 
    // 626: mandatory_expr_447 branches
    395, 448, 
    // 628: optional_repetitive_expr_448 branches
    395, 
    // 629: production_global_intro branches
    450, 
    // 630: alternative_expr_450 branches
    407, 440, 
    // 632: production_global_spec branches
    452, 
    // 633: mandatory_expr_452 branches
    453, 18, 267, 
    // 636: alternative_expr_453 branches
    454, 410, 
    // 638: production_global_scope branches
    456, 
    // 639: mandatory_expr_456 branches
    457, 458, 459, 
    // 642: optional_expr_457 branches
    451, 
    // 643: optional_repetitive_expr_458 branches
    449, 
    // 644: optional_repetitive_expr_459 branches
    446, 
    // 645: production_label_decl branches
    461, 
    // 646: mandatory_expr_461 branches
    18, 271, 
    // 648: production_call_stmt branches
    463, 
    // 649: mandatory_expr_463 branches
    464, 154, 267, 
    // 652: production_end branches
    466, 
    // 653: optional_expr_466 branches
    267, 
    // 654: production_block_or_stmt branches
    468, 
    // 655: alternative_expr_468 branches
    260, 537, 
    // 657: production_if_stmt branches
    470, 
    // 658: mandatory_expr_470 branches
    471, 243, 467, 474, 
    // 662: alternative_expr_471 branches
    472, 473, 
    // 664: optional_expr_474 branches
    475, 
    // 665: mandatory_expr_475 branches
    476, 467, 
    // 667: production_while_stmt branches
    478, 
    // 668: mandatory_expr_478 branches
    479, 243, 467, 
    // 671: alternative_expr_479 branches
    480, 481, 
    // 673: production_repeat_stmt branches
    483, 
    // 674: mandatory_expr_483 branches
    484, 260, 487, 243, 267, 
    // 679: alternative_expr_484 branches
    485, 486, 
    // 681: alternative_expr_487 branches
    480, 481, 
    // 683: production_loop_stmt branches
    489, 
    // 684: mandatory_expr_489 branches
    490, 467, 
    // 686: alternative_expr_490 branches
    491, 492, 
    // 688: production_for_stmt branches
    494, 
    // 689: mandatory_expr_494 branches
    495, 18, 59, 243, 496, 243, 486, 467, 
    // 697: alternative_expr_496 branches
    497, 498, 
    // 699: production_loop_control branches
    500, 
    // 700: mandatory_expr_500 branches
    501, 505, 267, 
    // 703: alternative_expr_501 branches
    502, 503, 504, 
    // 706: optional_expr_505 branches
    18, 
    // 707: production_loop_type_stmt branches
    507, 
    // 708: alternative_expr_507 branches
    477, 482, 488, 493, 499, 
    // 713: production_switch_case branches
    509, 
    // 714: mandatory_expr_509 branches
    510, 142, 271, 467, 
    // 718: production_default_case branches
    512, 
    // 719: mandatory_expr_512 branches
    255, 271, 467, 
    // 722: production_any_case branches
    514, 
    // 723: alternative_expr_514 branches
    508, 511, 
    // 725: production_case_list branches
    516, 
    // 726: mandatory_expr_516 branches
    513, 517, 
    // 728: optional_repetitive_expr_517 branches
    513, 
    // 729: production_switch_stmt branches
    519, 
    // 730: mandatory_expr_519 branches
    520, 243, 262, 515, 264, 
    // 735: production_goto_stmt branches
    522, 
    // 736: mandatory_expr_522 branches
    523, 18, 267, 
    // 739: alternative_expr_523 branches
    524, 525, 
    // 741: production_return_stmt branches
    527, 
    // 742: mandatory_expr_527 branches
    528, 267, 
    // 744: production_resultis_stmt branches
    530, 
    // 745: mandatory_expr_530 branches
    531, 245, 267, 
    // 748: production_delete_stmt branches
    533, 
    // 749: mandatory_expr_533 branches
    534, 287, 267, 
    // 752: production_flow_ctrl_stmt branches
    536, 
    // 753: alternative_expr_536 branches
    469, 506, 518, 521, 526, 529, 462, 532, 
    // 761: production_stmt branches
    538, 
    // 762: alternative_expr_538 branches
    397, 392, 535, 
    // 765: production_statement branches
    540, 
    // 766: mandatory_expr_540 branches
    541, 537, 
    // 768: optional_expr_541 branches
    460, 
    // 769: production_statement_list branches
    543, 
    // 770: mandatory_expr_543 branches
    539, 544, 
    // 772: optional_repetitive_expr_544 branches
    539, 
};

static const parsingnode_t parsingTable[545] = {
    // 0: production_int_lit
    { NC_PRODUCTION, NT_INT_LIT, TT_UNDEF, 0, 1, 0 },
    // 1: regex_terminal_1
    { NC_TERMINAL, NT_TERMINAL_1, TT_REGEX, "[0-9]+", 0, -1 },
    // 2: production_real_lit
    { NC_PRODUCTION, NT_REAL_LIT, TT_UNDEF, 0, 1, 1 },
    // 3: mandatory_expr_3
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 4, 2 },
    // 4: string_terminal_4
    { NC_TERMINAL, NT_TERMINAL_4, TT_STRING, ".", 0, -1 },
    // 5: optional_expr_5
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 6 },
    // 6: mandatory_expr_6
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 7 },
    // 7: regex_terminal_7
    { NC_TERMINAL, NT_TERMINAL_7, TT_REGEX, "[eE]", 0, -1 },
    // 8: optional_expr_8
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 10 },
    // 9: string_terminal_9
    { NC_TERMINAL, NT_TERMINAL_9, TT_STRING, "-", 0, -1 },
    // 10: production_str_lit
    { NC_PRODUCTION, NT_STR_LIT, TT_UNDEF, 0, 1, 11 },
    // 11: regex_terminal_11
    { NC_TERMINAL, NT_TERMINAL_11, TT_REGEX, "\"[^\"]+\"", 0, -1 },
    // 12: production_bool_lit
    { NC_PRODUCTION, NT_BOOL_LIT, TT_UNDEF, 0, 1, 12 },
    // 13: alternative_expr_13
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 13 },
    // 14: string_terminal_14
    { NC_TERMINAL, NT_TERMINAL_14, TT_STRING, "true", 0, -1 },
    // 15: string_terminal_15
    { NC_TERMINAL, NT_TERMINAL_15, TT_STRING, "false", 0, -1 },
    // 16: production_ptr_lit
    { NC_PRODUCTION, NT_PTR_LIT, TT_UNDEF, 0, 1, 15 },
    // 17: string_terminal_17
    { NC_TERMINAL, NT_TERMINAL_17, TT_STRING, "nil", 0, -1 },
    // 18: production_identifier
    { NC_PRODUCTION, NT_IDENTIFIER, TT_UNDEF, 0, 1, 16 },
    // 19: regex_terminal_19
    { NC_TERMINAL, NT_TERMINAL_19, TT_REGEX, "[a-zA-Z_][a-zA-Z0-9_]*", 0, -1 },
    // 20: production_base_type
    { NC_PRODUCTION, NT_BASE_TYPE, TT_UNDEF, 0, 1, 17 },
    // 21: alternative_expr_21
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 5, 18 },
    // 22: string_terminal_22
    { NC_TERMINAL, NT_TERMINAL_22, TT_STRING, "int", 0, -1 },
    // 23: string_terminal_23
    { NC_TERMINAL, NT_TERMINAL_23, TT_STRING, "real", 0, -1 },
    // 24: string_terminal_24
    { NC_TERMINAL, NT_TERMINAL_24, TT_STRING, "string", 0, -1 },
    // 25: string_terminal_25
    { NC_TERMINAL, NT_TERMINAL_25, TT_STRING, "byte", 0, -1 },
    // 26: string_terminal_26
    { NC_TERMINAL, NT_TERMINAL_26, TT_STRING, "bool", 0, -1 },
    // 27: production_object_pointer
    { NC_PRODUCTION, NT_OBJECT_POINTER, TT_UNDEF, 0, 1, 23 },
    // 28: mandatory_expr_28
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 24 },
    // 29: string_terminal_29
    { NC_TERMINAL, NT_TERMINAL_29, TT_STRING, "^", 0, -1 },
    // 30: production_cell_type
    { NC_PRODUCTION, NT_CELL_TYPE, TT_UNDEF, 0, 1, 26 },
    // 31: alternative_expr_31
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 27 },
    // 32: production_cell_pointer
    { NC_PRODUCTION, NT_CELL_POINTER, TT_UNDEF, 0, 1, 29 },
    // 33: mandatory_expr_33
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 30 },
    // 34: string_terminal_34
    { NC_TERMINAL, NT_TERMINAL_34, TT_STRING, "*", 0, -1 },
    // 35: production_type
    { NC_PRODUCTION, NT_TYPE, TT_UNDEF, 0, 1, 32 },
    // 36: alternative_expr_36
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 33 },
    // 37: production_type_list
    { NC_PRODUCTION, NT_TYPE_LIST, TT_UNDEF, 0, 1, 36 },
    // 38: mandatory_expr_38
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 37 },
    // 39: optional_repetitive_expr_39
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 39 },
    // 40: mandatory_expr_40
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 40 },
    // 41: string_terminal_41
    { NC_TERMINAL, NT_TERMINAL_41, TT_STRING, ",", 0, -1 },
    // 42: production_neg_op
    { NC_PRODUCTION, NT_NEG_OP, TT_UNDEF, 0, 1, 42 },
    // 43: alternative_expr_43
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 43 },
    // 44: string_terminal_44
    { NC_TERMINAL, NT_TERMINAL_44, TT_STRING, "-", 0, -1 },
    // 45: string_terminal_45
    { NC_TERMINAL, NT_TERMINAL_45, TT_STRING, "not", 0, -1 },
    // 46: production_mult_op
    { NC_PRODUCTION, NT_MULT_OP, TT_UNDEF, 0, 1, 45 },
    // 47: alternative_expr_47
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 46 },
    // 48: string_terminal_48
    { NC_TERMINAL, NT_TERMINAL_48, TT_STRING, "/", 0, -1 },
    // 49: string_terminal_49
    { NC_TERMINAL, NT_TERMINAL_49, TT_STRING, "mod", 0, -1 },
    // 50: production_add_op
    { NC_PRODUCTION, NT_ADD_OP, TT_UNDEF, 0, 1, 49 },
    // 51: alternative_expr_51
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 50 },
    // 52: string_terminal_52
    { NC_TERMINAL, NT_TERMINAL_52, TT_STRING, "+", 0, -1 },
    // 53: production_shf_op
    { NC_PRODUCTION, NT_SHF_OP, TT_UNDEF, 0, 1, 52 },
    // 54: alternative_expr_54
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 53 },
    // 55: string_terminal_55
    { NC_TERMINAL, NT_TERMINAL_55, TT_STRING, "shl", 0, -1 },
    // 56: string_terminal_56
    { NC_TERMINAL, NT_TERMINAL_56, TT_STRING, "shr", 0, -1 },
    // 57: production_cmp_op
    { NC_PRODUCTION, NT_CMP_OP, TT_UNDEF, 0, 1, 55 },
    // 58: alternative_expr_58
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 6, 56 },
    // 59: string_terminal_59
    { NC_TERMINAL, NT_TERMINAL_59, TT_STRING, "=", 0, -1 },
    // 60: string_terminal_60
    { NC_TERMINAL, NT_TERMINAL_60, TT_STRING, "<>", 0, -1 },
    // 61: string_terminal_61
    { NC_TERMINAL, NT_TERMINAL_61, TT_STRING, "<", 0, -1 },
    // 62: string_terminal_62
    { NC_TERMINAL, NT_TERMINAL_62, TT_STRING, ">", 0, -1 },
    // 63: string_terminal_63
    { NC_TERMINAL, NT_TERMINAL_63, TT_STRING, "<=", 0, -1 },
    // 64: string_terminal_64
    { NC_TERMINAL, NT_TERMINAL_64, TT_STRING, ">=", 0, -1 },
    // 65: production_and_op
    { NC_PRODUCTION, NT_AND_OP, TT_UNDEF, 0, 1, 62 },
    // 66: string_terminal_66
    { NC_TERMINAL, NT_TERMINAL_66, TT_STRING, "and", 0, -1 },
    // 67: production_or_op
    { NC_PRODUCTION, NT_OR_OP, TT_UNDEF, 0, 1, 63 },
    // 68: alternative_expr_68
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 64 },
    // 69: string_terminal_69
    { NC_TERMINAL, NT_TERMINAL_69, TT_STRING, "or", 0, -1 },
    // 70: string_terminal_70
    { NC_TERMINAL, NT_TERMINAL_70, TT_STRING, "xor", 0, -1 },
    // 71: production_c_num_base_e
    { NC_PRODUCTION, NT_C_NUM_BASE_E, TT_UNDEF, 0, 1, 66 },
    // 72: alternative_expr_72
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 4, 67 },
    // 73: mandatory_expr_73
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 71 },
    // 74: string_terminal_74
    { NC_TERMINAL, NT_TERMINAL_74, TT_STRING, "(", 0, -1 },
    // 75: string_terminal_75
    { NC_TERMINAL, NT_TERMINAL_75, TT_STRING, ")", 0, -1 },
    // 76: production_c_num_neg_e
    { NC_PRODUCTION, NT_C_NUM_NEG_E, TT_UNDEF, 0, 1, 74 },
    // 77: mandatory_expr_77
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 75 },
    // 78: optional_expr_78
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 77 },
    // 79: production_c_num_mult_e
    { NC_PRODUCTION, NT_C_NUM_MULT_E, TT_UNDEF, 0, 1, 78 },
    // 80: mandatory_expr_80
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 79 },
    // 81: optional_repetitive_expr_81
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 81 },
    // 82: mandatory_expr_82
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 82 },
    // 83: production_c_num_add_e
    { NC_PRODUCTION, NT_C_NUM_ADD_E, TT_UNDEF, 0, 1, 84 },
    // 84: mandatory_expr_84
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 85 },
    // 85: optional_repetitive_expr_85
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 87 },
    // 86: mandatory_expr_86
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 88 },
    // 87: production_c_num_shf_e
    { NC_PRODUCTION, NT_C_NUM_SHF_E, TT_UNDEF, 0, 1, 90 },
    // 88: mandatory_expr_88
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 91 },
    // 89: optional_expr_89
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 93 },
    // 90: mandatory_expr_90
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 94 },
    // 91: production_c_num_cmp_e
    { NC_PRODUCTION, NT_C_NUM_CMP_E, TT_UNDEF, 0, 1, 96 },
    // 92: mandatory_expr_92
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 97 },
    // 93: optional_expr_93
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 99 },
    // 94: mandatory_expr_94
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 100 },
    // 95: production_c_num_and_e
    { NC_PRODUCTION, NT_C_NUM_AND_E, TT_UNDEF, 0, 1, 102 },
    // 96: mandatory_expr_96
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 103 },
    // 97: optional_repetitive_expr_97
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 105 },
    // 98: mandatory_expr_98
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 106 },
    // 99: production_c_num_or_e
    { NC_PRODUCTION, NT_C_NUM_OR_E, TT_UNDEF, 0, 1, 108 },
    // 100: mandatory_expr_100
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 109 },
    // 101: optional_repetitive_expr_101
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 111 },
    // 102: mandatory_expr_102
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 112 },
    // 103: production_c_num_e
    { NC_PRODUCTION, NT_C_NUM_E, TT_UNDEF, 0, 1, 114 },
    // 104: production_c_str_base_e
    { NC_PRODUCTION, NT_C_STR_BASE_E, TT_UNDEF, 0, 1, 115 },
    // 105: alternative_expr_105
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 116 },
    // 106: production_c_str_add_e
    { NC_PRODUCTION, NT_C_STR_ADD_E, TT_UNDEF, 0, 1, 118 },
    // 107: mandatory_expr_107
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 119 },
    // 108: optional_repetitive_expr_108
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 121 },
    // 109: mandatory_expr_109
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 122 },
    // 110: string_terminal_110
    { NC_TERMINAL, NT_TERMINAL_110, TT_STRING, "+", 0, -1 },
    // 111: production_c_str_cmp_e
    { NC_PRODUCTION, NT_C_STR_CMP_E, TT_UNDEF, 0, 1, 124 },
    // 112: mandatory_expr_112
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 125 },
    // 113: optional_expr_113
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 127 },
    // 114: mandatory_expr_114
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 128 },
    // 115: production_c_str_and_e
    { NC_PRODUCTION, NT_C_STR_AND_E, TT_UNDEF, 0, 1, 130 },
    // 116: mandatory_expr_116
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 131 },
    // 117: optional_repetitive_expr_117
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 133 },
    // 118: mandatory_expr_118
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 134 },
    // 119: production_c_str_or_e
    { NC_PRODUCTION, NT_C_STR_OR_E, TT_UNDEF, 0, 1, 136 },
    // 120: mandatory_expr_120
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 137 },
    // 121: optional_repetitive_expr_121
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 139 },
    // 122: mandatory_expr_122
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 140 },
    // 123: production_c_str_e
    { NC_PRODUCTION, NT_C_STR_E, TT_UNDEF, 0, 1, 142 },
    // 124: production_c_bool_base_e
    { NC_PRODUCTION, NT_C_BOOL_BASE_E, TT_UNDEF, 0, 1, 143 },
    // 125: alternative_expr_125
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 144 },
    // 126: production_c_bool_not_e
    { NC_PRODUCTION, NT_C_BOOL_NOT_E, TT_UNDEF, 0, 1, 146 },
    // 127: mandatory_expr_127
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 147 },
    // 128: optional_expr_128
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 149 },
    // 129: string_terminal_129
    { NC_TERMINAL, NT_TERMINAL_129, TT_STRING, "not", 0, -1 },
    // 130: production_c_bool_and_e
    { NC_PRODUCTION, NT_C_BOOL_AND_E, TT_UNDEF, 0, 1, 150 },
    // 131: mandatory_expr_131
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 151 },
    // 132: optional_repetitive_expr_132
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 153 },
    // 133: mandatory_expr_133
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 154 },
    // 134: production_c_bool_or_e
    { NC_PRODUCTION, NT_C_BOOL_OR_E, TT_UNDEF, 0, 1, 156 },
    // 135: mandatory_expr_135
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 157 },
    // 136: optional_repetitive_expr_136
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 159 },
    // 137: mandatory_expr_137
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 160 },
    // 138: production_c_bool_e
    { NC_PRODUCTION, NT_C_BOOL_E, TT_UNDEF, 0, 1, 162 },
    // 139: production_c_ptr_e
    { NC_PRODUCTION, NT_C_PTR_E, TT_UNDEF, 0, 1, 163 },
    // 140: production_const_expr
    { NC_PRODUCTION, NT_CONST_EXPR, TT_UNDEF, 0, 1, 164 },
    // 141: alternative_expr_141
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 4, 165 },
    // 142: production_c_expr_list
    { NC_PRODUCTION, NT_C_EXPR_LIST, TT_UNDEF, 0, 1, 169 },
    // 143: mandatory_expr_143
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 170 },
    // 144: optional_repetitive_expr_144
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 172 },
    // 145: mandatory_expr_145
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 173 },
    // 146: string_terminal_146
    { NC_TERMINAL, NT_TERMINAL_146, TT_STRING, ",", 0, -1 },
    // 147: production_access_op
    { NC_PRODUCTION, NT_ACCESS_OP, TT_UNDEF, 0, 1, 175 },
    // 148: alternative_expr_148
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 176 },
    // 149: mandatory_expr_149
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 178 },
    // 150: string_terminal_150
    { NC_TERMINAL, NT_TERMINAL_150, TT_STRING, "->", 0, -1 },
    // 151: mandatory_expr_151
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 180 },
    // 152: string_terminal_152
    { NC_TERMINAL, NT_TERMINAL_152, TT_STRING, "[", 0, -1 },
    // 153: string_terminal_153
    { NC_TERMINAL, NT_TERMINAL_153, TT_STRING, "]", 0, -1 },
    // 154: production_ident_access
    { NC_PRODUCTION, NT_IDENT_ACCESS, TT_UNDEF, 0, 1, 183 },
    // 155: mandatory_expr_155
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 184 },
    // 156: optional_repetitive_expr_156
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 187 },
    // 157: optional_expr_157
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 188 },
    // 158: mandatory_expr_158
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 189 },
    // 159: string_terminal_159
    { NC_TERMINAL, NT_TERMINAL_159, TT_STRING, "(", 0, -1 },
    // 160: optional_expr_160
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 192 },
    // 161: string_terminal_161
    { NC_TERMINAL, NT_TERMINAL_161, TT_STRING, ")", 0, -1 },
    // 162: production_valof_expr
    { NC_PRODUCTION, NT_VALOF_EXPR, TT_UNDEF, 0, 1, 193 },
    // 163: mandatory_expr_163
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 194 },
    // 164: string_terminal_164
    { NC_TERMINAL, NT_TERMINAL_164, TT_STRING, "valof", 0, -1 },
    // 165: production_num_base_e
    { NC_PRODUCTION, NT_NUM_BASE_E, TT_UNDEF, 0, 1, 197 },
    // 166: alternative_expr_166
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 5, 198 },
    // 167: mandatory_expr_167
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 203 },
    // 168: production_num_neg_e
    { NC_PRODUCTION, NT_NUM_NEG_E, TT_UNDEF, 0, 1, 206 },
    // 169: mandatory_expr_169
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 207 },
    // 170: optional_expr_170
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 209 },
    // 171: production_num_mult_e
    { NC_PRODUCTION, NT_NUM_MULT_E, TT_UNDEF, 0, 1, 210 },
    // 172: mandatory_expr_172
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 211 },
    // 173: optional_repetitive_expr_173
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 213 },
    // 174: mandatory_expr_174
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 214 },
    // 175: production_num_add_e
    { NC_PRODUCTION, NT_NUM_ADD_E, TT_UNDEF, 0, 1, 216 },
    // 176: mandatory_expr_176
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 217 },
    // 177: optional_repetitive_expr_177
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 219 },
    // 178: mandatory_expr_178
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 220 },
    // 179: production_num_shf_e
    { NC_PRODUCTION, NT_NUM_SHF_E, TT_UNDEF, 0, 1, 222 },
    // 180: mandatory_expr_180
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 223 },
    // 181: optional_expr_181
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 225 },
    // 182: mandatory_expr_182
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 226 },
    // 183: production_num_cmp_e
    { NC_PRODUCTION, NT_NUM_CMP_E, TT_UNDEF, 0, 1, 228 },
    // 184: mandatory_expr_184
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 229 },
    // 185: optional_expr_185
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 231 },
    // 186: mandatory_expr_186
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 232 },
    // 187: production_num_and_e
    { NC_PRODUCTION, NT_NUM_AND_E, TT_UNDEF, 0, 1, 234 },
    // 188: mandatory_expr_188
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 235 },
    // 189: optional_repetitive_expr_189
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 237 },
    // 190: mandatory_expr_190
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 238 },
    // 191: production_num_or_e
    { NC_PRODUCTION, NT_NUM_OR_E, TT_UNDEF, 0, 1, 240 },
    // 192: mandatory_expr_192
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 241 },
    // 193: optional_repetitive_expr_193
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 243 },
    // 194: mandatory_expr_194
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 244 },
    // 195: production_num_e
    { NC_PRODUCTION, NT_NUM_E, TT_UNDEF, 0, 1, 246 },
    // 196: production_str_base_e
    { NC_PRODUCTION, NT_STR_BASE_E, TT_UNDEF, 0, 1, 247 },
    // 197: alternative_expr_197
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 248 },
    // 198: production_str_add_e
    { NC_PRODUCTION, NT_STR_ADD_E, TT_UNDEF, 0, 1, 251 },
    // 199: mandatory_expr_199
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 252 },
    // 200: optional_repetitive_expr_200
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 254 },
    // 201: mandatory_expr_201
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 255 },
    // 202: production_str_cmp_e
    { NC_PRODUCTION, NT_STR_CMP_E, TT_UNDEF, 0, 1, 257 },
    // 203: mandatory_expr_203
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 258 },
    // 204: optional_expr_204
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 260 },
    // 205: mandatory_expr_205
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 261 },
    // 206: production_str_and_e
    { NC_PRODUCTION, NT_STR_AND_E, TT_UNDEF, 0, 1, 263 },
    // 207: mandatory_expr_207
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 264 },
    // 208: optional_repetitive_expr_208
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 266 },
    // 209: mandatory_expr_209
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 267 },
    // 210: production_str_or_e
    { NC_PRODUCTION, NT_STR_OR_E, TT_UNDEF, 0, 1, 269 },
    // 211: mandatory_expr_211
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 270 },
    // 212: optional_repetitive_expr_212
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 272 },
    // 213: mandatory_expr_213
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 273 },
    // 214: production_str_e
    { NC_PRODUCTION, NT_STR_E, TT_UNDEF, 0, 1, 275 },
    // 215: production_bool_base_e
    { NC_PRODUCTION, NT_BOOL_BASE_E, TT_UNDEF, 0, 1, 276 },
    // 216: alternative_expr_216
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 277 },
    // 217: production_bool_not_e
    { NC_PRODUCTION, NT_BOOL_NOT_E, TT_UNDEF, 0, 1, 280 },
    // 218: mandatory_expr_218
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 281 },
    // 219: optional_expr_219
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 283 },
    // 220: production_bool_and_e
    { NC_PRODUCTION, NT_BOOL_AND_E, TT_UNDEF, 0, 1, 284 },
    // 221: mandatory_expr_221
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 285 },
    // 222: optional_repetitive_expr_222
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 287 },
    // 223: mandatory_expr_223
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 288 },
    // 224: production_bool_or_e
    { NC_PRODUCTION, NT_BOOL_OR_E, TT_UNDEF, 0, 1, 290 },
    // 225: mandatory_expr_225
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 291 },
    // 226: optional_repetitive_expr_226
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 293 },
    // 227: mandatory_expr_227
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 294 },
    // 228: production_bool_e
    { NC_PRODUCTION, NT_BOOL_E, TT_UNDEF, 0, 1, 296 },
    // 229: production_array_inst
    { NC_PRODUCTION, NT_ARRAY_INST, TT_UNDEF, 0, 1, 297 },
    // 230: mandatory_expr_230
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 298 },
    // 231: alternative_expr_231
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 301 },
    // 232: string_terminal_232
    { NC_TERMINAL, NT_TERMINAL_232, TT_STRING, "dynamic", 0, -1 },
    // 233: string_terminal_233
    { NC_TERMINAL, NT_TERMINAL_233, TT_STRING, "assoc", 0, -1 },
    // 234: production_object_inst
    { NC_PRODUCTION, NT_OBJECT_INST, TT_UNDEF, 0, 1, 304 },
    // 235: mandatory_expr_235
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 305 },
    // 236: optional_expr_236
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 308 },
    // 237: production_ptr_e
    { NC_PRODUCTION, NT_PTR_E, TT_UNDEF, 0, 1, 309 },
    // 238: alternative_expr_238
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 310 },
    // 239: mandatory_expr_239
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 312 },
    // 240: string_terminal_240
    { NC_TERMINAL, NT_TERMINAL_240, TT_STRING, "new", 0, -1 },
    // 241: optional_expr_241
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 315 },
    // 242: alternative_expr_242
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 316 },
    // 243: production_expr
    { NC_PRODUCTION, NT_EXPR, TT_UNDEF, 0, 1, 318 },
    // 244: alternative_expr_244
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 4, 319 },
    // 245: production_expr_list
    { NC_PRODUCTION, NT_EXPR_LIST, TT_UNDEF, 0, 1, 323 },
    // 246: mandatory_expr_246
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 324 },
    // 247: optional_repetitive_expr_247
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 326 },
    // 248: mandatory_expr_248
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 327 },
    // 249: production_call_arg
    { NC_PRODUCTION, NT_CALL_ARG, TT_UNDEF, 0, 1, 329 },
    // 250: mandatory_expr_250
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 330 },
    // 251: optional_expr_251
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 332 },
    // 252: mandatory_expr_252
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 333 },
    // 253: string_terminal_253
    { NC_TERMINAL, NT_TERMINAL_253, TT_STRING, "=>", 0, -1 },
    // 254: alternative_expr_254
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 335 },
    // 255: string_terminal_255
    { NC_TERMINAL, NT_TERMINAL_255, TT_STRING, "default", 0, -1 },
    // 256: production_call_arg_list
    { NC_PRODUCTION, NT_CALL_ARG_LIST, TT_UNDEF, 0, 1, 337 },
    // 257: mandatory_expr_257
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 338 },
    // 258: optional_repetitive_expr_258
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 340 },
    // 259: mandatory_expr_259
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 341 },
    // 260: production_block
    { NC_PRODUCTION, NT_BLOCK, TT_UNDEF, 0, 1, 343 },
    // 261: mandatory_expr_261
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 344 },
    // 262: string_terminal_262
    { NC_TERMINAL, NT_TERMINAL_262, TT_STRING, "{", 0, -1 },
    // 263: optional_expr_263
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 347 },
    // 264: string_terminal_264
    { NC_TERMINAL, NT_TERMINAL_264, TT_STRING, "}", 0, -1 },
    // 265: production_optional_block
    { NC_PRODUCTION, NT_OPTIONAL_BLOCK, TT_UNDEF, 0, 1, 348 },
    // 266: alternative_expr_266
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 349 },
    // 267: string_terminal_267
    { NC_TERMINAL, NT_TERMINAL_267, TT_STRING, ";", 0, -1 },
    // 268: production_argument_decl
    { NC_PRODUCTION, NT_ARGUMENT_DECL, TT_UNDEF, 0, 1, 351 },
    // 269: alternative_expr_269
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 352 },
    // 270: mandatory_expr_270
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 4, 354 },
    // 271: string_terminal_271
    { NC_TERMINAL, NT_TERMINAL_271, TT_STRING, ":", 0, -1 },
    // 272: optional_expr_272
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 358 },
    // 273: mandatory_expr_273
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 359 },
    // 274: string_terminal_274
    { NC_TERMINAL, NT_TERMINAL_274, TT_STRING, "=", 0, -1 },
    // 275: string_terminal_275
    { NC_TERMINAL, NT_TERMINAL_275, TT_STRING, "...", 0, -1 },
    // 276: production_argument_list
    { NC_PRODUCTION, NT_ARGUMENT_LIST, TT_UNDEF, 0, 1, 361 },
    // 277: mandatory_expr_277
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 362 },
    // 278: optional_repetitive_expr_278
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 364 },
    // 279: mandatory_expr_279
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 365 },
    // 280: string_terminal_280
    { NC_TERMINAL, NT_TERMINAL_280, TT_STRING, ";", 0, -1 },
    // 281: production_arg_declarator
    { NC_PRODUCTION, NT_ARG_DECLARATOR, TT_UNDEF, 0, 1, 367 },
    // 282: mandatory_expr_282
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 368 },
    // 283: optional_expr_283
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 371 },
    // 284: production_return_decl
    { NC_PRODUCTION, NT_RETURN_DECL, TT_UNDEF, 0, 1, 372 },
    // 285: mandatory_expr_285
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 373 },
    // 286: string_terminal_286
    { NC_TERMINAL, NT_TERMINAL_286, TT_STRING, "returning", 0, -1 },
    // 287: production_ident_list
    { NC_PRODUCTION, NT_IDENT_LIST, TT_UNDEF, 0, 1, 375 },
    // 288: mandatory_expr_288
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 376 },
    // 289: optional_repetitive_expr_289
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 378 },
    // 290: mandatory_expr_290
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 379 },
    // 291: production_extends_clause
    { NC_PRODUCTION, NT_EXTENDS_CLAUSE, TT_UNDEF, 0, 1, 381 },
    // 292: mandatory_expr_292
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 382 },
    // 293: string_terminal_293
    { NC_TERMINAL, NT_TERMINAL_293, TT_STRING, "extends", 0, -1 },
    // 294: production_impl_clause
    { NC_PRODUCTION, NT_IMPL_CLAUSE, TT_UNDEF, 0, 1, 384 },
    // 295: mandatory_expr_295
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 385 },
    // 296: string_terminal_296
    { NC_TERMINAL, NT_TERMINAL_296, TT_STRING, "implements", 0, -1 },
    // 297: production_visibility
    { NC_PRODUCTION, NT_VISIBILITY, TT_UNDEF, 0, 1, 387 },
    // 298: alternative_expr_298
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 388 },
    // 299: string_terminal_299
    { NC_TERMINAL, NT_TERMINAL_299, TT_STRING, "private", 0, -1 },
    // 300: string_terminal_300
    { NC_TERMINAL, NT_TERMINAL_300, TT_STRING, "protected", 0, -1 },
    // 301: string_terminal_301
    { NC_TERMINAL, NT_TERMINAL_301, TT_STRING, "public", 0, -1 },
    // 302: production_access_type
    { NC_PRODUCTION, NT_ACCESS_TYPE, TT_UNDEF, 0, 1, 391 },
    // 303: alternative_expr_303
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 392 },
    // 304: string_terminal_304
    { NC_TERMINAL, NT_TERMINAL_304, TT_STRING, "readonly", 0, -1 },
    // 305: string_terminal_305
    { NC_TERMINAL, NT_TERMINAL_305, TT_STRING, "readwrite", 0, -1 },
    // 306: string_terminal_306
    { NC_TERMINAL, NT_TERMINAL_306, TT_STRING, "writeonly", 0, -1 },
    // 307: production_storage_type
    { NC_PRODUCTION, NT_STORAGE_TYPE, TT_UNDEF, 0, 1, 395 },
    // 308: string_terminal_308
    { NC_TERMINAL, NT_TERMINAL_308, TT_STRING, "static", 0, -1 },
    // 309: production_derivation
    { NC_PRODUCTION, NT_DERIVATION, TT_UNDEF, 0, 1, 396 },
    // 310: alternative_expr_310
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 397 },
    // 311: string_terminal_311
    { NC_TERMINAL, NT_TERMINAL_311, TT_STRING, "override", 0, -1 },
    // 312: string_terminal_312
    { NC_TERMINAL, NT_TERMINAL_312, TT_STRING, "final", 0, -1 },
    // 313: production_implementation
    { NC_PRODUCTION, NT_IMPLEMENTATION, TT_UNDEF, 0, 1, 399 },
    // 314: string_terminal_314
    { NC_TERMINAL, NT_TERMINAL_314, TT_STRING, "implementation", 0, -1 },
    // 315: production_attrib_flag
    { NC_PRODUCTION, NT_ATTRIB_FLAG, TT_UNDEF, 0, 1, 400 },
    // 316: alternative_expr_316
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 5, 401 },
    // 317: production_attrib_flags
    { NC_PRODUCTION, NT_ATTRIB_FLAGS, TT_UNDEF, 0, 1, 406 },
    // 318: mandatory_expr_318
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 407 },
    // 319: optional_repetitive_expr_319
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 409 },
    // 320: production_attrib_decl
    { NC_PRODUCTION, NT_ATTRIB_DECL, TT_UNDEF, 0, 1, 410 },
    // 321: mandatory_expr_321
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 7, 411 },
    // 322: optional_expr_322
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 418 },
    // 323: string_terminal_323
    { NC_TERMINAL, NT_TERMINAL_323, TT_STRING, "attribute", 0, -1 },
    // 324: string_terminal_324
    { NC_TERMINAL, NT_TERMINAL_324, TT_STRING, ":", 0, -1 },
    // 325: optional_expr_325
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 419 },
    // 326: mandatory_expr_326
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 420 },
    // 327: production_method_flag
    { NC_PRODUCTION, NT_METHOD_FLAG, TT_UNDEF, 0, 1, 422 },
    // 328: alternative_expr_328
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 4, 423 },
    // 329: production_method_flags
    { NC_PRODUCTION, NT_METHOD_FLAGS, TT_UNDEF, 0, 1, 427 },
    // 330: mandatory_expr_330
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 428 },
    // 331: optional_repetitive_expr_331
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 430 },
    // 332: production_method_decl
    { NC_PRODUCTION, NT_METHOD_DECL, TT_UNDEF, 0, 1, 431 },
    // 333: mandatory_expr_333
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 6, 432 },
    // 334: optional_expr_334
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 438 },
    // 335: string_terminal_335
    { NC_TERMINAL, NT_TERMINAL_335, TT_STRING, "method", 0, -1 },
    // 336: optional_expr_336
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 439 },
    // 337: production_field
    { NC_PRODUCTION, NT_FIELD, TT_UNDEF, 0, 1, 440 },
    // 338: alternative_expr_338
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 4, 441 },
    // 339: production_field_list
    { NC_PRODUCTION, NT_FIELD_LIST, TT_UNDEF, 0, 1, 445 },
    // 340: mandatory_expr_340
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 446 },
    // 341: optional_repetitive_expr_341
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 448 },
    // 342: production_class_decl
    { NC_PRODUCTION, NT_CLASS_DECL, TT_UNDEF, 0, 1, 449 },
    // 343: mandatory_expr_343
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 7, 450 },
    // 344: string_terminal_344
    { NC_TERMINAL, NT_TERMINAL_344, TT_STRING, "class", 0, -1 },
    // 345: optional_expr_345
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 457 },
    // 346: optional_expr_346
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 458 },
    // 347: string_terminal_347
    { NC_TERMINAL, NT_TERMINAL_347, TT_STRING, "{", 0, -1 },
    // 348: optional_expr_348
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 459 },
    // 349: string_terminal_349
    { NC_TERMINAL, NT_TERMINAL_349, TT_STRING, "}", 0, -1 },
    // 350: production_iattrib_decl
    { NC_PRODUCTION, NT_IATTRIB_DECL, TT_UNDEF, 0, 1, 460 },
    // 351: mandatory_expr_351
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 6, 461 },
    // 352: optional_expr_352
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 467 },
    // 353: production_imethod_decl
    { NC_PRODUCTION, NT_IMETHOD_DECL, TT_UNDEF, 0, 1, 468 },
    // 354: mandatory_expr_354
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 5, 469 },
    // 355: optional_expr_355
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 474 },
    // 356: production_ifield
    { NC_PRODUCTION, NT_IFIELD, TT_UNDEF, 0, 1, 475 },
    // 357: alternative_expr_357
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 4, 476 },
    // 358: production_ifield_list
    { NC_PRODUCTION, NT_IFIELD_LIST, TT_UNDEF, 0, 1, 480 },
    // 359: mandatory_expr_359
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 481 },
    // 360: optional_repetitive_expr_360
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 483 },
    // 361: production_interface_decl
    { NC_PRODUCTION, NT_INTERFACE_DECL, TT_UNDEF, 0, 1, 484 },
    // 362: mandatory_expr_362
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 6, 485 },
    // 363: string_terminal_363
    { NC_TERMINAL, NT_TERMINAL_363, TT_STRING, "interface", 0, -1 },
    // 364: optional_expr_364
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 491 },
    // 365: optional_expr_365
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 492 },
    // 366: production_func_decl
    { NC_PRODUCTION, NT_FUNC_DECL, TT_UNDEF, 0, 1, 493 },
    // 367: mandatory_expr_367
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 6, 494 },
    // 368: optional_expr_368
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 500 },
    // 369: string_terminal_369
    { NC_TERMINAL, NT_TERMINAL_369, TT_STRING, "function", 0, -1 },
    // 370: production_proc_decl
    { NC_PRODUCTION, NT_PROC_DECL, TT_UNDEF, 0, 1, 501 },
    // 371: mandatory_expr_371
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 5, 502 },
    // 372: optional_expr_372
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 507 },
    // 373: string_terminal_373
    { NC_TERMINAL, NT_TERMINAL_373, TT_STRING, "procedure", 0, -1 },
    // 374: production_var_decl
    { NC_PRODUCTION, NT_VAR_DECL, TT_UNDEF, 0, 1, 508 },
    // 375: mandatory_expr_375
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 5, 509 },
    // 376: string_terminal_376
    { NC_TERMINAL, NT_TERMINAL_376, TT_STRING, "var", 0, -1 },
    // 377: production_const_decl
    { NC_PRODUCTION, NT_CONST_DECL, TT_UNDEF, 0, 1, 514 },
    // 378: mandatory_expr_378
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 5, 515 },
    // 379: string_terminal_379
    { NC_TERMINAL, NT_TERMINAL_379, TT_STRING, "const", 0, -1 },
    // 380: production_enum_item
    { NC_PRODUCTION, NT_ENUM_ITEM, TT_UNDEF, 0, 1, 520 },
    // 381: mandatory_expr_381
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 521 },
    // 382: optional_expr_382
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 523 },
    // 383: mandatory_expr_383
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 524 },
    // 384: production_enum_item_list
    { NC_PRODUCTION, NT_ENUM_ITEM_LIST, TT_UNDEF, 0, 1, 526 },
    // 385: mandatory_expr_385
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 527 },
    // 386: optional_repetitive_expr_386
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 530 },
    // 387: mandatory_expr_387
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 531 },
    // 388: optional_expr_388
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 533 },
    // 389: production_enum_decl
    { NC_PRODUCTION, NT_ENUM_DECL, TT_UNDEF, 0, 1, 534 },
    // 390: mandatory_expr_390
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 5, 535 },
    // 391: string_terminal_391
    { NC_TERMINAL, NT_TERMINAL_391, TT_STRING, "enum", 0, -1 },
    // 392: production_let_stmt
    { NC_PRODUCTION, NT_LET_STMT, TT_UNDEF, 0, 1, 540 },
    // 393: mandatory_expr_393
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 5, 541 },
    // 394: string_terminal_394
    { NC_TERMINAL, NT_TERMINAL_394, TT_STRING, "let", 0, -1 },
    // 395: production_decl_stmt
    { NC_PRODUCTION, NT_DECL_STMT, TT_UNDEF, 0, 1, 546 },
    // 396: alternative_expr_396
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 7, 547 },
    // 397: production_block_decl
    { NC_PRODUCTION, NT_BLOCK_DECL, TT_UNDEF, 0, 1, 554 },
    // 398: alternative_expr_398
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 555 },
    // 399: production_import_path
    { NC_PRODUCTION, NT_IMPORT_PATH, TT_UNDEF, 0, 1, 558 },
    // 400: mandatory_expr_400
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 559 },
    // 401: optional_repetitive_expr_401
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 561 },
    // 402: mandatory_expr_402
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 562 },
    // 403: production_import_list
    { NC_PRODUCTION, NT_IMPORT_LIST, TT_UNDEF, 0, 1, 564 },
    // 404: mandatory_expr_404
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 565 },
    // 405: optional_repetitive_expr_405
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 567 },
    // 406: mandatory_expr_406
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 568 },
    // 407: production_import_stmt
    { NC_PRODUCTION, NT_IMPORT_STMT, TT_UNDEF, 0, 1, 570 },
    // 408: mandatory_expr_408
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 571 },
    // 409: string_terminal_409
    { NC_TERMINAL, NT_TERMINAL_409, TT_STRING, "import", 0, -1 },
    // 410: production_xref_type
    { NC_PRODUCTION, NT_XREF_TYPE, TT_UNDEF, 0, 1, 574 },
    // 411: alternative_expr_411
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 575 },
    // 412: string_terminal_412
    { NC_TERMINAL, NT_TERMINAL_412, TT_STRING, "module", 0, -1 },
    // 413: string_terminal_413
    { NC_TERMINAL, NT_TERMINAL_413, TT_STRING, "package", 0, -1 },
    // 414: string_terminal_414
    { NC_TERMINAL, NT_TERMINAL_414, TT_STRING, "library", 0, -1 },
    // 415: production_str_lit_list
    { NC_PRODUCTION, NT_STR_LIT_LIST, TT_UNDEF, 0, 1, 578 },
    // 416: mandatory_expr_416
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 579 },
    // 417: optional_repetitive_expr_417
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 581 },
    // 418: mandatory_expr_418
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 582 },
    // 419: production_platform_spec
    { NC_PRODUCTION, NT_PLATFORM_SPEC, TT_UNDEF, 0, 1, 584 },
    // 420: mandatory_expr_420
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 585 },
    // 421: string_terminal_421
    { NC_TERMINAL, NT_TERMINAL_421, TT_STRING, "platform", 0, -1 },
    // 422: production_language_spec
    { NC_PRODUCTION, NT_LANGUAGE_SPEC, TT_UNDEF, 0, 1, 587 },
    // 423: mandatory_expr_423
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 588 },
    // 424: string_terminal_424
    { NC_TERMINAL, NT_TERMINAL_424, TT_STRING, "language", 0, -1 },
    // 425: production_header_spec
    { NC_PRODUCTION, NT_HEADER_SPEC, TT_UNDEF, 0, 1, 590 },
    // 426: mandatory_expr_426
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 591 },
    // 427: string_terminal_427
    { NC_TERMINAL, NT_TERMINAL_427, TT_STRING, "header", 0, -1 },
    // 428: production_function_spec
    { NC_PRODUCTION, NT_FUNCTION_SPEC, TT_UNDEF, 0, 1, 593 },
    // 429: mandatory_expr_429
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 594 },
    // 430: production_procedure_spec
    { NC_PRODUCTION, NT_PROCEDURE_SPEC, TT_UNDEF, 0, 1, 596 },
    // 431: mandatory_expr_431
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 597 },
    // 432: production_class_spec
    { NC_PRODUCTION, NT_CLASS_SPEC, TT_UNDEF, 0, 1, 599 },
    // 433: mandatory_expr_433
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 600 },
    // 434: production_alien_spec
    { NC_PRODUCTION, NT_ALIEN_SPEC, TT_UNDEF, 0, 1, 602 },
    // 435: alternative_expr_435
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 6, 603 },
    // 436: production_alien_specs
    { NC_PRODUCTION, NT_ALIEN_SPECS, TT_UNDEF, 0, 1, 609 },
    // 437: mandatory_expr_437
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 610 },
    // 438: optional_repetitive_expr_438
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 612 },
    // 439: mandatory_expr_439
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 613 },
    // 440: production_alien_stmt
    { NC_PRODUCTION, NT_ALIEN_STMT, TT_UNDEF, 0, 1, 615 },
    // 441: mandatory_expr_441
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 5, 616 },
    // 442: string_terminal_442
    { NC_TERMINAL, NT_TERMINAL_442, TT_STRING, "alien", 0, -1 },
    // 443: optional_expr_443
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 621 },
    // 444: mandatory_expr_444
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 622 },
    // 445: production_global_stmt
    { NC_PRODUCTION, NT_GLOBAL_STMT, TT_UNDEF, 0, 1, 624 },
    // 446: production_global_stmts
    { NC_PRODUCTION, NT_GLOBAL_STMTS, TT_UNDEF, 0, 1, 625 },
    // 447: mandatory_expr_447
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 626 },
    // 448: optional_repetitive_expr_448
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 628 },
    // 449: production_global_intro
    { NC_PRODUCTION, NT_GLOBAL_INTRO, TT_UNDEF, 0, 1, 629 },
    // 450: alternative_expr_450
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 630 },
    // 451: production_global_spec
    { NC_PRODUCTION, NT_GLOBAL_SPEC, TT_UNDEF, 0, 1, 632 },
    // 452: mandatory_expr_452
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 633 },
    // 453: alternative_expr_453
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 636 },
    // 454: string_terminal_454
    { NC_TERMINAL, NT_TERMINAL_454, TT_STRING, "program", 0, -1 },
    // 455: production_global_scope
    { NC_PRODUCTION, NT_GLOBAL_SCOPE, TT_UNDEF, 0, 1, 638 },
    // 456: mandatory_expr_456
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 639 },
    // 457: optional_expr_457
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 642 },
    // 458: optional_repetitive_expr_458
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 643 },
    // 459: optional_repetitive_expr_459
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 644 },
    // 460: production_label_decl
    { NC_PRODUCTION, NT_LABEL_DECL, TT_UNDEF, 0, 1, 645 },
    // 461: mandatory_expr_461
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 646 },
    // 462: production_call_stmt
    { NC_PRODUCTION, NT_CALL_STMT, TT_UNDEF, 0, 1, 648 },
    // 463: mandatory_expr_463
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 649 },
    // 464: string_terminal_464
    { NC_TERMINAL, NT_TERMINAL_464, TT_STRING, "call", 0, -1 },
    // 465: production_end
    { NC_PRODUCTION, NT_END, TT_UNDEF, 0, 1, 652 },
    // 466: optional_expr_466
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 653 },
    // 467: production_block_or_stmt
    { NC_PRODUCTION, NT_BLOCK_OR_STMT, TT_UNDEF, 0, 1, 654 },
    // 468: alternative_expr_468
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 655 },
    // 469: production_if_stmt
    { NC_PRODUCTION, NT_IF_STMT, TT_UNDEF, 0, 1, 657 },
    // 470: mandatory_expr_470
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 4, 658 },
    // 471: alternative_expr_471
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 662 },
    // 472: string_terminal_472
    { NC_TERMINAL, NT_TERMINAL_472, TT_STRING, "if", 0, -1 },
    // 473: string_terminal_473
    { NC_TERMINAL, NT_TERMINAL_473, TT_STRING, "unless", 0, -1 },
    // 474: optional_expr_474
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 664 },
    // 475: mandatory_expr_475
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 665 },
    // 476: string_terminal_476
    { NC_TERMINAL, NT_TERMINAL_476, TT_STRING, "else", 0, -1 },
    // 477: production_while_stmt
    { NC_PRODUCTION, NT_WHILE_STMT, TT_UNDEF, 0, 1, 667 },
    // 478: mandatory_expr_478
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 668 },
    // 479: alternative_expr_479
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 671 },
    // 480: string_terminal_480
    { NC_TERMINAL, NT_TERMINAL_480, TT_STRING, "while", 0, -1 },
    // 481: string_terminal_481
    { NC_TERMINAL, NT_TERMINAL_481, TT_STRING, "until", 0, -1 },
    // 482: production_repeat_stmt
    { NC_PRODUCTION, NT_REPEAT_STMT, TT_UNDEF, 0, 1, 673 },
    // 483: mandatory_expr_483
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 5, 674 },
    // 484: alternative_expr_484
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 679 },
    // 485: string_terminal_485
    { NC_TERMINAL, NT_TERMINAL_485, TT_STRING, "repeat", 0, -1 },
    // 486: string_terminal_486
    { NC_TERMINAL, NT_TERMINAL_486, TT_STRING, "do", 0, -1 },
    // 487: alternative_expr_487
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 681 },
    // 488: production_loop_stmt
    { NC_PRODUCTION, NT_LOOP_STMT, TT_UNDEF, 0, 1, 683 },
    // 489: mandatory_expr_489
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 684 },
    // 490: alternative_expr_490
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 686 },
    // 491: string_terminal_491
    { NC_TERMINAL, NT_TERMINAL_491, TT_STRING, "loop", 0, -1 },
    // 492: string_terminal_492
    { NC_TERMINAL, NT_TERMINAL_492, TT_STRING, "forever", 0, -1 },
    // 493: production_for_stmt
    { NC_PRODUCTION, NT_FOR_STMT, TT_UNDEF, 0, 1, 688 },
    // 494: mandatory_expr_494
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 8, 689 },
    // 495: string_terminal_495
    { NC_TERMINAL, NT_TERMINAL_495, TT_STRING, "for", 0, -1 },
    // 496: alternative_expr_496
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 697 },
    // 497: string_terminal_497
    { NC_TERMINAL, NT_TERMINAL_497, TT_STRING, "to", 0, -1 },
    // 498: string_terminal_498
    { NC_TERMINAL, NT_TERMINAL_498, TT_STRING, "downto", 0, -1 },
    // 499: production_loop_control
    { NC_PRODUCTION, NT_LOOP_CONTROL, TT_UNDEF, 0, 1, 699 },
    // 500: mandatory_expr_500
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 700 },
    // 501: alternative_expr_501
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 703 },
    // 502: string_terminal_502
    { NC_TERMINAL, NT_TERMINAL_502, TT_STRING, "break", 0, -1 },
    // 503: string_terminal_503
    { NC_TERMINAL, NT_TERMINAL_503, TT_STRING, "continue", 0, -1 },
    // 504: string_terminal_504
    { NC_TERMINAL, NT_TERMINAL_504, TT_STRING, "again", 0, -1 },
    // 505: optional_expr_505
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 706 },
    // 506: production_loop_type_stmt
    { NC_PRODUCTION, NT_LOOP_TYPE_STMT, TT_UNDEF, 0, 1, 707 },
    // 507: alternative_expr_507
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 5, 708 },
    // 508: production_switch_case
    { NC_PRODUCTION, NT_SWITCH_CASE, TT_UNDEF, 0, 1, 713 },
    // 509: mandatory_expr_509
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 4, 714 },
    // 510: string_terminal_510
    { NC_TERMINAL, NT_TERMINAL_510, TT_STRING, "case", 0, -1 },
    // 511: production_default_case
    { NC_PRODUCTION, NT_DEFAULT_CASE, TT_UNDEF, 0, 1, 718 },
    // 512: mandatory_expr_512
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 719 },
    // 513: production_any_case
    { NC_PRODUCTION, NT_ANY_CASE, TT_UNDEF, 0, 1, 722 },
    // 514: alternative_expr_514
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 723 },
    // 515: production_case_list
    { NC_PRODUCTION, NT_CASE_LIST, TT_UNDEF, 0, 1, 725 },
    // 516: mandatory_expr_516
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 726 },
    // 517: optional_repetitive_expr_517
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 728 },
    // 518: production_switch_stmt
    { NC_PRODUCTION, NT_SWITCH_STMT, TT_UNDEF, 0, 1, 729 },
    // 519: mandatory_expr_519
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 5, 730 },
    // 520: string_terminal_520
    { NC_TERMINAL, NT_TERMINAL_520, TT_STRING, "switch", 0, -1 },
    // 521: production_goto_stmt
    { NC_PRODUCTION, NT_GOTO_STMT, TT_UNDEF, 0, 1, 735 },
    // 522: mandatory_expr_522
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 736 },
    // 523: alternative_expr_523
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 2, 739 },
    // 524: string_terminal_524
    { NC_TERMINAL, NT_TERMINAL_524, TT_STRING, "goto", 0, -1 },
    // 525: string_terminal_525
    { NC_TERMINAL, NT_TERMINAL_525, TT_STRING, "gosub", 0, -1 },
    // 526: production_return_stmt
    { NC_PRODUCTION, NT_RETURN_STMT, TT_UNDEF, 0, 1, 741 },
    // 527: mandatory_expr_527
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 742 },
    // 528: string_terminal_528
    { NC_TERMINAL, NT_TERMINAL_528, TT_STRING, "return", 0, -1 },
    // 529: production_resultis_stmt
    { NC_PRODUCTION, NT_RESULTIS_STMT, TT_UNDEF, 0, 1, 744 },
    // 530: mandatory_expr_530
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 745 },
    // 531: string_terminal_531
    { NC_TERMINAL, NT_TERMINAL_531, TT_STRING, "resultis", 0, -1 },
    // 532: production_delete_stmt
    { NC_PRODUCTION, NT_DELETE_STMT, TT_UNDEF, 0, 1, 748 },
    // 533: mandatory_expr_533
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 3, 749 },
    // 534: string_terminal_534
    { NC_TERMINAL, NT_TERMINAL_534, TT_STRING, "delete", 0, -1 },
    // 535: production_flow_ctrl_stmt
    { NC_PRODUCTION, NT_FLOW_CTRL_STMT, TT_UNDEF, 0, 1, 752 },
    // 536: alternative_expr_536
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 8, 753 },
    // 537: production_stmt
    { NC_PRODUCTION, NT_STMT, TT_UNDEF, 0, 1, 761 },
    // 538: alternative_expr_538
    { NC_ALTERNATIVE, _NT_GENERIC, TT_UNDEF, 0, 3, 762 },
    // 539: production_statement
    { NC_PRODUCTION, NT_STATEMENT, TT_UNDEF, 0, 1, 765 },
    // 540: mandatory_expr_540
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 766 },
    // 541: optional_expr_541
    { NC_OPTIONAL, _NT_GENERIC, TT_UNDEF, 0, 1, 768 },
    // 542: production_statement_list
    { NC_PRODUCTION, NT_STATEMENT_LIST, TT_UNDEF, 0, 1, 769 },
    // 543: mandatory_expr_543
    { NC_MANDATORY, _NT_GENERIC, TT_UNDEF, 0, 2, 770 },
    // 544: optional_repetitive_expr_544
    { NC_OPTIONAL_REPETITIVE, _NT_GENERIC, TT_UNDEF, 0, 1, 772 },
};

