#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <stdio.h>

typedef struct _line_t {
    struct _line_t* next;
    char*           buf;
} line_t;

static line_t* first = 0;
static line_t* last  = 0;

static void enterline( const char* text ) {
    size_t  len  = strlen( text ) + 1U;
    line_t* line = (line_t*) malloc( sizeof(line_t) + len );
    if ( line == 0 ) {
        fprintf( stderr, "out of memory\n" );
        exit( EXIT_FAILURE );
    }
    line->next = 0;
    line->buf  = ((char*)line) + sizeof(line_t);
    memcpy( line->buf, text, len );
    if ( first == 0 ) {
        first = last = line;
    } else {
        last->next = line;
        last       = line;
    }
}

int main( int argc, char** argv ) {

    FILE* fp = fopen( "parsingtable.c", "rt" );
    if ( fp == 0 ) {
        fprintf( stderr, "failed to open parsing table: %m\n" );
        return EXIT_FAILURE;
    }

    char linebuf[512];
    while ( fgets( linebuf, 512, fp ) ) {
        enterline( linebuf );
    }
    
    fclose( fp );

    FILE* fph = fopen( "parsingtable.h", "wt" );
    if ( fph == 0 ) {
        fprintf( stderr, "failed to create parsing table header file: %m\n" );
        return EXIT_FAILURE;
    }

    fprintf( fph, "%s", 
        "// do not modify -- autogenerated by separateparsingtable\n\n"
        "#ifndef PARSINGTABLE_H\n"
        "#define PARSINGTABLE_H     1\n\n"
    );

    fp = fopen( "parsingtable.c", "wt" );
    if ( fp == 0 ) {
        fprintf( stderr, "failed to create parsing table file: %m\n" );
        return EXIT_FAILURE;
    }

    fprintf( fp, "%s",
        "// do not modify -- autogenerated by separateparsingtable\n\n"
        "#include \"parsingtable.h\"\n\n"
    );

    line_t* line = first; bool pastheader = false;
    while ( line ) {
        if ( strncmp( line->buf, "// branches", 11 ) == 0 ) pastheader = true;
        if ( !pastheader ) {
            fprintf( fph, "%s", line->buf );
        } else {
            fprintf( fp, "%s", line->buf );
        }
        line = line->next;
    }

    fclose( fp );

    fprintf( fph, "%s",
        "\n#endif\n\n"
    );
    fclose( fph );

    return EXIT_SUCCESS;
}